-- ============================================================
-- Fase 1: Unificar las 4 tablas de ingredientes en recipe_ingredients
-- ============================================================
-- Tablas eliminadas: diet_plan_recipe_ingredients, private_recipe_ingredients,
--                   free_recipe_ingredients, recipe_ingredients (legacy template)
-- Tabla creada:     recipe_ingredients (unificada con 4 FKs nullable)
-- Vistas creadas:   diet_plan_recipe_ingredients, private_recipe_ingredients,
--                   free_recipe_ingredients (para compatibilidad con funciones DB)
-- ============================================================

BEGIN;

-- ── 1. Crear tabla unificada ──────────────────────────────────────────────────

CREATE TABLE recipe_ingredients_new (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Exactamente uno de estos debe ser no-null (garantizado por CHECK)
  recipe_id           bigint,   -- templates (→ recipes)
  diet_plan_recipe_id bigint,   -- personalizadas en plan (→ diet_plan_recipes)
  private_recipe_id   bigint,   -- recetas privadas del usuario (→ private_recipes)
  free_recipe_id      bigint,   -- recetas libres del usuario (→ free_recipes)

  -- Campos comunes
  food_id             bigint REFERENCES food(id) ON DELETE CASCADE,
  grams               numeric(10,2) NOT NULL DEFAULT 0,

  -- Campos específicos de tipo (NULL en los demás)
  food_group_id       bigint REFERENCES food_groups(id),  -- solo templates
  status              text DEFAULT 'linked'
                      CHECK (status IN ('linked', 'pending', 'rejected')),  -- solo free
  created_at          timestamp with time zone DEFAULT now(),

  CONSTRAINT ri_exactly_one_parent CHECK (
    (recipe_id IS NOT NULL)::int +
    (diet_plan_recipe_id IS NOT NULL)::int +
    (private_recipe_id IS NOT NULL)::int +
    (free_recipe_id IS NOT NULL)::int = 1
  ),
  CONSTRAINT ri_recipe_id_fkey
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
  CONSTRAINT ri_diet_plan_recipe_id_fkey
    FOREIGN KEY (diet_plan_recipe_id) REFERENCES diet_plan_recipes(id) ON DELETE CASCADE,
  CONSTRAINT ri_private_recipe_id_fkey
    FOREIGN KEY (private_recipe_id) REFERENCES private_recipes(id) ON DELETE CASCADE,
  CONSTRAINT ri_free_recipe_id_fkey
    FOREIGN KEY (free_recipe_id) REFERENCES free_recipes(id) ON DELETE CASCADE
);

ALTER TABLE recipe_ingredients_new OWNER TO postgres;


-- ── 2. Migrar datos de las 4 tablas originales ───────────────────────────────

-- 2a. Templates (recipe_ingredients → recipe_id)
INSERT INTO recipe_ingredients_new (recipe_id, food_id, grams, food_group_id)
SELECT recipe_id,
       food_id,
       COALESCE(grams, 0)::numeric(10,2),
       food_group_id
FROM recipe_ingredients
WHERE food_id IS NOT NULL;

-- 2b. Plan (diet_plan_recipe_ingredients → diet_plan_recipe_id)
INSERT INTO recipe_ingredients_new (diet_plan_recipe_id, food_id, grams, created_at)
SELECT diet_plan_recipe_id,
       food_id,
       COALESCE(grams, 0),
       COALESCE(created_at, now())
FROM diet_plan_recipe_ingredients
WHERE food_id IS NOT NULL;

-- 2c. Private (private_recipe_ingredients → private_recipe_id)
INSERT INTO recipe_ingredients_new (private_recipe_id, food_id, grams)
SELECT private_recipe_id,
       food_id,
       grams
FROM private_recipe_ingredients
WHERE food_id IS NOT NULL;

-- 2d. Free (free_recipe_ingredients → free_recipe_id)
--     Incluye food_id NULL (ingredientes pendientes de vincular)
INSERT INTO recipe_ingredients_new (free_recipe_id, food_id, grams, status, created_at)
SELECT free_recipe_id,
       food_id,   -- puede ser NULL
       grams,
       COALESCE(status, 'linked'),
       COALESCE(created_at, now())
FROM free_recipe_ingredients;

-- Verificación rápida (comentar en producción)
DO $$
DECLARE
  total_old bigint;
  total_new bigint;
BEGIN
  SELECT
    (SELECT COUNT(*) FROM recipe_ingredients WHERE food_id IS NOT NULL) +
    (SELECT COUNT(*) FROM diet_plan_recipe_ingredients WHERE food_id IS NOT NULL) +
    (SELECT COUNT(*) FROM private_recipe_ingredients WHERE food_id IS NOT NULL) +
    (SELECT COUNT(*) FROM free_recipe_ingredients)
  INTO total_old;

  SELECT COUNT(*) INTO total_new FROM recipe_ingredients_new;

  IF total_old <> total_new THEN
    RAISE EXCEPTION 'Migración de datos incompleta: esperados %, migrados %', total_old, total_new;
  END IF;
END;
$$;


-- ── 3. Renombrar tablas ───────────────────────────────────────────────────────

ALTER TABLE recipe_ingredients RENAME TO recipe_ingredients_legacy;
ALTER TABLE recipe_ingredients_new RENAME TO recipe_ingredients;


-- ── 4. Índices ────────────────────────────────────────────────────────────────

CREATE INDEX idx_ri_recipe_id
  ON recipe_ingredients(recipe_id)
  WHERE recipe_id IS NOT NULL;

CREATE INDEX idx_ri_diet_plan_recipe_id
  ON recipe_ingredients(diet_plan_recipe_id)
  WHERE diet_plan_recipe_id IS NOT NULL;

CREATE INDEX idx_ri_private_recipe_id
  ON recipe_ingredients(private_recipe_id)
  WHERE private_recipe_id IS NOT NULL;

CREATE INDEX idx_ri_free_recipe_id
  ON recipe_ingredients(free_recipe_id)
  WHERE free_recipe_id IS NOT NULL;

CREATE INDEX idx_ri_food_id
  ON recipe_ingredients(food_id);


-- ── 5. RLS ────────────────────────────────────────────────────────────────────

ALTER TABLE recipe_ingredients ENABLE ROW LEVEL SECURITY;

-- Admin: acceso total
CREATE POLICY "Admin full access on recipe_ingredients"
  ON recipe_ingredients
  USING (is_admin())
  WITH CHECK (is_admin());

-- Admin o coach: lectura/escritura
CREATE POLICY "Admin or coach can manage recipe_ingredients"
  ON recipe_ingredients
  USING (is_admin_or_coach())
  WITH CHECK (is_admin_or_coach());

-- Usuarios: leer ingredientes de templates globales
CREATE POLICY "Users can read template recipe_ingredients"
  ON recipe_ingredients
  FOR SELECT
  USING (recipe_id IS NOT NULL AND auth.role() = 'authenticated');

-- Usuarios: gestionar ingredientes de sus recetas en plan
CREATE POLICY "Users can manage their own diet plan recipe ingredients"
  ON recipe_ingredients
  USING (
    diet_plan_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM diet_plan_recipes dpr
      JOIN diet_plans dp ON dpr.diet_plan_id = dp.id
      WHERE dpr.id = recipe_ingredients.diet_plan_recipe_id
        AND dp.user_id = auth.uid()
    )
  );

-- Usuarios: gestionar sus recetas privadas
CREATE POLICY "Users can manage their own private recipe ingredients"
  ON recipe_ingredients
  USING (
    private_recipe_id IS NOT NULL AND
    (is_admin() OR EXISTS (
      SELECT 1 FROM private_recipes pr
      WHERE pr.id = recipe_ingredients.private_recipe_id
        AND pr.user_id = auth.uid()
    ))
  )
  WITH CHECK (
    private_recipe_id IS NOT NULL AND
    (is_admin() OR EXISTS (
      SELECT 1 FROM private_recipes pr
      WHERE pr.id = recipe_ingredients.private_recipe_id
        AND pr.user_id = auth.uid()
    ))
  );

-- Usuarios: gestionar sus recetas libres
CREATE POLICY "Users can manage their own free recipe ingredients"
  ON recipe_ingredients
  USING (
    free_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM free_recipes fm
      WHERE fm.id = recipe_ingredients.free_recipe_id
        AND fm.user_id = auth.uid()
    )
  )
  WITH CHECK (
    free_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM free_recipes fm
      WHERE fm.id = recipe_ingredients.free_recipe_id
        AND fm.user_id = auth.uid()
    )
  );

-- Coaches: gestionar ingredientes de recetas en plan de sus clientes
CREATE POLICY "Coaches can manage client diet plan recipe ingredients"
  ON recipe_ingredients
  USING (
    diet_plan_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1
      FROM diet_plan_recipes
      JOIN diet_plans ON diet_plan_recipes.diet_plan_id = diet_plans.id
      JOIN coach_clients ON diet_plans.user_id = coach_clients.client_id
      WHERE diet_plan_recipes.id = recipe_ingredients.diet_plan_recipe_id
        AND coach_clients.coach_id = auth.uid()
    )
  );

-- Coaches: gestionar ingredientes en sus propias plantillas
CREATE POLICY "Coaches can manage ingredients in their own templates"
  ON recipe_ingredients
  USING (
    diet_plan_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM diet_plan_recipes dpr
      JOIN diet_plans dp ON dpr.diet_plan_id = dp.id
      WHERE dpr.id = recipe_ingredients.diet_plan_recipe_id
        AND dp.is_template = true
        AND dp.created_by = auth.uid()
    )
  );

-- Coaches: gestionar recetas privadas de sus clientes
CREATE POLICY "Coaches can manage client private recipe ingredients"
  ON recipe_ingredients
  USING (
    private_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM private_recipes pr
      JOIN coach_clients cc ON pr.user_id = cc.client_id
      WHERE pr.id = recipe_ingredients.private_recipe_id
        AND cc.coach_id = auth.uid()
    )
  );

-- Coaches: gestionar recetas libres de sus clientes
CREATE POLICY "Coaches can manage client free recipe ingredients"
  ON recipe_ingredients
  USING (
    free_recipe_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM free_recipes fr
      JOIN coach_clients cc ON fr.user_id = cc.client_id
      WHERE fr.id = recipe_ingredients.free_recipe_id
        AND cc.coach_id = auth.uid()
    )
  );


-- ── 6. Eliminar tablas antiguas ───────────────────────────────────────────────
-- CASCADE elimina automáticamente índices, políticas y constraints asociados

DROP TABLE diet_plan_recipe_ingredients CASCADE;
DROP TABLE private_recipe_ingredients CASCADE;
DROP TABLE free_recipe_ingredients CASCADE;
DROP TABLE recipe_ingredients_legacy CASCADE;


-- ── 7. Vistas de compatibilidad para funciones DB existentes ─────────────────
--
-- Las funciones DB (SECURITY DEFINER) siguen usando los nombres de tabla
-- originales. Las vistas + triggers INSTEAD OF redirigen a la tabla unificada.
-- El frontend ya no usará estas vistas (usa recipe_ingredients directamente).

-- 7a. diet_plan_recipe_ingredients
CREATE VIEW diet_plan_recipe_ingredients AS
  SELECT id,
         diet_plan_recipe_id,
         food_id,
         grams,
         created_at
  FROM recipe_ingredients
  WHERE diet_plan_recipe_id IS NOT NULL;

CREATE OR REPLACE FUNCTION _trig_dpri_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO recipe_ingredients (diet_plan_recipe_id, food_id, grams, created_at)
  VALUES (
    NEW.diet_plan_recipe_id,
    NEW.food_id,
    COALESCE(NEW.grams, 0),
    COALESCE(NEW.created_at, now())
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION _trig_dpri_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  UPDATE recipe_ingredients
  SET food_id = NEW.food_id, grams = COALESCE(NEW.grams, 0)
  WHERE id = OLD.id;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION _trig_dpri_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM recipe_ingredients WHERE id = OLD.id;
  RETURN OLD;
END;
$$;

CREATE TRIGGER trig_dpri_insert
  INSTEAD OF INSERT ON diet_plan_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_dpri_insert();

CREATE TRIGGER trig_dpri_update
  INSTEAD OF UPDATE ON diet_plan_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_dpri_update();

CREATE TRIGGER trig_dpri_delete
  INSTEAD OF DELETE ON diet_plan_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_dpri_delete();


-- 7b. private_recipe_ingredients
CREATE VIEW private_recipe_ingredients AS
  SELECT id,
         private_recipe_id,
         food_id,
         grams
  FROM recipe_ingredients
  WHERE private_recipe_id IS NOT NULL;

CREATE OR REPLACE FUNCTION _trig_pri_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO recipe_ingredients (private_recipe_id, food_id, grams)
  VALUES (NEW.private_recipe_id, NEW.food_id, COALESCE(NEW.grams, 0));
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION _trig_pri_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  UPDATE recipe_ingredients
  SET food_id = NEW.food_id, grams = COALESCE(NEW.grams, 0)
  WHERE id = OLD.id;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION _trig_pri_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM recipe_ingredients WHERE id = OLD.id;
  RETURN OLD;
END;
$$;

CREATE TRIGGER trig_pri_insert
  INSTEAD OF INSERT ON private_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_pri_insert();

CREATE TRIGGER trig_pri_update
  INSTEAD OF UPDATE ON private_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_pri_update();

CREATE TRIGGER trig_pri_delete
  INSTEAD OF DELETE ON private_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_pri_delete();


-- 7c. free_recipe_ingredients
CREATE VIEW free_recipe_ingredients AS
  SELECT id,
         free_recipe_id,
         food_id,
         grams,
         status,
         created_at
  FROM recipe_ingredients
  WHERE free_recipe_id IS NOT NULL;

CREATE OR REPLACE FUNCTION _trig_fri_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO recipe_ingredients (free_recipe_id, food_id, grams, status, created_at)
  VALUES (
    NEW.free_recipe_id,
    NEW.food_id,   -- puede ser NULL para ingredientes pendientes
    COALESCE(NEW.grams, 0),
    COALESCE(NEW.status, 'linked'),
    COALESCE(NEW.created_at, now())
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION _trig_fri_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  UPDATE recipe_ingredients
  SET food_id = NEW.food_id,
      grams   = COALESCE(NEW.grams, 0),
      status  = COALESCE(NEW.status, 'linked')
  WHERE id = OLD.id;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION _trig_fri_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM recipe_ingredients WHERE id = OLD.id;
  RETURN OLD;
END;
$$;

CREATE TRIGGER trig_fri_insert
  INSTEAD OF INSERT ON free_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_fri_insert();

CREATE TRIGGER trig_fri_update
  INSTEAD OF UPDATE ON free_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_fri_update();

CREATE TRIGGER trig_fri_delete
  INSTEAD OF DELETE ON free_recipe_ingredients
  FOR EACH ROW EXECUTE FUNCTION _trig_fri_delete();


COMMIT;
