begin;

create table if not exists public.feature_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature_key text not null check (feature_key in ('my_plan_autobalance', 'recipe_equivalence_autobalance')),
  operation_id uuid not null,
  origin text not null default 'other',
  metadata jsonb not null default '{}'::jsonb,
  consumed boolean not null default true,
  blocked_reason text check (blocked_reason in ('quota_exceeded', 'not_limited_role', 'operation_failed')),
  limit_at_time integer,
  remaining_after integer,
  role_at_time text,
  created_at timestamptz not null default now(),
  unique (user_id, feature_key, operation_id)
);

create index if not exists idx_feature_usage_events_user_feature_created
  on public.feature_usage_events (user_id, feature_key, created_at desc);

alter table public.feature_usage_events enable row level security;

drop policy if exists "Users can read own feature usage events" on public.feature_usage_events;
create policy "Users can read own feature usage events"
on public.feature_usage_events
for select
using (auth.uid() = user_id);

drop policy if exists "Admins can read all feature usage events" on public.feature_usage_events;
create policy "Admins can read all feature usage events"
on public.feature_usage_events
for select
using (public.is_admin());

create or replace function public.get_autobalance_feature_limit(
  p_feature_key text,
  p_role text
)
returns integer
language sql
immutable
as $$
  select case
    when lower(coalesce(p_role, 'free')) <> 'free' then null
    when lower(coalesce(p_feature_key, '')) = 'my_plan_autobalance' then 3
    when lower(coalesce(p_feature_key, '')) = 'recipe_equivalence_autobalance' then 10
    else null
  end;
$$;

create or replace function public.get_autobalance_quota_snapshot()
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_my_plan_limit integer;
  v_recipe_eq_limit integer;
  v_my_plan_used integer := 0;
  v_recipe_eq_used integer := 0;
  v_my_plan_remaining integer;
  v_recipe_eq_remaining integer;
  v_is_limited boolean;
begin
  if v_uid is null then
    raise exception 'Authentication required.';
  end if;

  select lower(r.role)
  into v_role
  from public.user_roles ur
  join public.roles r on r.id = ur.role_id
  where ur.user_id = v_uid
  limit 1;

  v_role := coalesce(v_role, 'free');
  v_is_limited := (v_role = 'free');

  select
    count(*) filter (where feature_key = 'my_plan_autobalance' and consumed = true),
    count(*) filter (where feature_key = 'recipe_equivalence_autobalance' and consumed = true)
  into v_my_plan_used, v_recipe_eq_used
  from public.feature_usage_events
  where user_id = v_uid;

  v_my_plan_limit := public.get_autobalance_feature_limit('my_plan_autobalance', v_role);
  v_recipe_eq_limit := public.get_autobalance_feature_limit('recipe_equivalence_autobalance', v_role);

  v_my_plan_remaining := case
    when v_my_plan_limit is null then null
    else greatest(v_my_plan_limit - v_my_plan_used, 0)
  end;

  v_recipe_eq_remaining := case
    when v_recipe_eq_limit is null then null
    else greatest(v_recipe_eq_limit - v_recipe_eq_used, 0)
  end;

  return jsonb_build_object(
    'role', v_role,
    'is_free_limited', v_is_limited,
    'quotas', jsonb_build_object(
      'my_plan_autobalance', jsonb_build_object(
        'feature_key', 'my_plan_autobalance',
        'is_limited', v_is_limited,
        'limit', v_my_plan_limit,
        'used', case when v_is_limited then v_my_plan_used else 0 end,
        'remaining', v_my_plan_remaining,
        'blocked', (v_is_limited and coalesce(v_my_plan_remaining, 0) <= 0)
      ),
      'recipe_equivalence_autobalance', jsonb_build_object(
        'feature_key', 'recipe_equivalence_autobalance',
        'is_limited', v_is_limited,
        'limit', v_recipe_eq_limit,
        'used', case when v_is_limited then v_recipe_eq_used else 0 end,
        'remaining', v_recipe_eq_remaining,
        'blocked', (v_is_limited and coalesce(v_recipe_eq_remaining, 0) <= 0)
      )
    )
  );
end;
$$;

create or replace function public.consume_autobalance_quota(
  p_feature_key text,
  p_operation_id uuid default null,
  p_origin text default 'other',
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_feature_key text := lower(trim(coalesce(p_feature_key, '')));
  v_operation_id uuid := coalesce(p_operation_id, gen_random_uuid());
  v_limit integer;
  v_used integer := 0;
  v_remaining integer;
  v_existing record;
begin
  if v_uid is null then
    raise exception 'Authentication required.';
  end if;

  if v_feature_key not in ('my_plan_autobalance', 'recipe_equivalence_autobalance') then
    raise exception 'Unknown feature key: %', v_feature_key;
  end if;

  select lower(r.role)
  into v_role
  from public.user_roles ur
  join public.roles r on r.id = ur.role_id
  where ur.user_id = v_uid
  limit 1;

  v_role := coalesce(v_role, 'free');

  -- Idempotencia: misma operación no vuelve a cobrar.
  select consumed, blocked_reason, remaining_after, limit_at_time
  into v_existing
  from public.feature_usage_events
  where user_id = v_uid
    and feature_key = v_feature_key
    and operation_id = v_operation_id
  limit 1;

  if found then
    return jsonb_build_object(
      'success', true,
      'feature_key', v_feature_key,
      'operation_id', v_operation_id,
      'is_limited', (v_role = 'free'),
      'allowed', coalesce(v_existing.consumed, false),
      'consumed', coalesce(v_existing.consumed, false),
      'remaining', v_existing.remaining_after,
      'limit', v_existing.limit_at_time,
      'reason', coalesce(v_existing.blocked_reason, 'already_consumed')
    );
  end if;

  -- Roles no free: ilimitado (sin consumo real).
  if v_role <> 'free' then
    insert into public.feature_usage_events (
      user_id,
      feature_key,
      operation_id,
      origin,
      metadata,
      consumed,
      blocked_reason,
      limit_at_time,
      remaining_after,
      role_at_time
    ) values (
      v_uid,
      v_feature_key,
      v_operation_id,
      coalesce(nullif(trim(p_origin), ''), 'other'),
      coalesce(p_metadata, '{}'::jsonb),
      false,
      'not_limited_role',
      null,
      null,
      v_role
    )
    on conflict (user_id, feature_key, operation_id) do nothing;

    return jsonb_build_object(
      'success', true,
      'feature_key', v_feature_key,
      'operation_id', v_operation_id,
      'is_limited', false,
      'allowed', true,
      'consumed', false,
      'remaining', null,
      'limit', null,
      'reason', 'unlimited_role'
    );
  end if;

  v_limit := public.get_autobalance_feature_limit(v_feature_key, v_role);
  if v_limit is null then
    raise exception 'Missing feature limit for key: %', v_feature_key;
  end if;

  -- Evita doble consumo en clics concurrentes sobre el mismo bucket.
  perform pg_advisory_xact_lock(hashtext(v_uid::text || ':' || v_feature_key));

  -- Re-check tras lock para idempotencia fuerte.
  select consumed, blocked_reason, remaining_after, limit_at_time
  into v_existing
  from public.feature_usage_events
  where user_id = v_uid
    and feature_key = v_feature_key
    and operation_id = v_operation_id
  limit 1;

  if found then
    return jsonb_build_object(
      'success', true,
      'feature_key', v_feature_key,
      'operation_id', v_operation_id,
      'is_limited', true,
      'allowed', coalesce(v_existing.consumed, false),
      'consumed', coalesce(v_existing.consumed, false),
      'remaining', v_existing.remaining_after,
      'limit', v_existing.limit_at_time,
      'reason', coalesce(v_existing.blocked_reason, 'already_consumed')
    );
  end if;

  select count(*)
  into v_used
  from public.feature_usage_events
  where user_id = v_uid
    and feature_key = v_feature_key
    and consumed = true;

  if v_used >= v_limit then
    insert into public.feature_usage_events (
      user_id,
      feature_key,
      operation_id,
      origin,
      metadata,
      consumed,
      blocked_reason,
      limit_at_time,
      remaining_after,
      role_at_time
    ) values (
      v_uid,
      v_feature_key,
      v_operation_id,
      coalesce(nullif(trim(p_origin), ''), 'other'),
      coalesce(p_metadata, '{}'::jsonb),
      false,
      'quota_exceeded',
      v_limit,
      0,
      v_role
    )
    on conflict (user_id, feature_key, operation_id) do nothing;

    return jsonb_build_object(
      'success', true,
      'feature_key', v_feature_key,
      'operation_id', v_operation_id,
      'is_limited', true,
      'allowed', false,
      'consumed', false,
      'remaining', 0,
      'limit', v_limit,
      'reason', 'quota_exceeded'
    );
  end if;

  v_remaining := greatest(v_limit - (v_used + 1), 0);

  insert into public.feature_usage_events (
    user_id,
    feature_key,
    operation_id,
    origin,
    metadata,
    consumed,
    blocked_reason,
    limit_at_time,
    remaining_after,
    role_at_time
  ) values (
    v_uid,
    v_feature_key,
    v_operation_id,
    coalesce(nullif(trim(p_origin), ''), 'other'),
    coalesce(p_metadata, '{}'::jsonb),
    true,
    null,
    v_limit,
    v_remaining,
    v_role
  )
  on conflict (user_id, feature_key, operation_id) do nothing;

  return jsonb_build_object(
    'success', true,
    'feature_key', v_feature_key,
    'operation_id', v_operation_id,
    'is_limited', true,
    'allowed', true,
    'consumed', true,
    'remaining', v_remaining,
    'limit', v_limit,
    'reason', 'consumed'
  );
end;
$$;

create or replace function public.release_autobalance_quota(
  p_feature_key text,
  p_operation_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_feature_key text := lower(trim(coalesce(p_feature_key, '')));
  v_updated integer := 0;
begin
  if v_uid is null then
    raise exception 'Authentication required.';
  end if;

  if v_feature_key not in ('my_plan_autobalance', 'recipe_equivalence_autobalance') then
    raise exception 'Unknown feature key: %', v_feature_key;
  end if;

  if p_operation_id is null then
    return jsonb_build_object(
      'success', false,
      'refunded', false,
      'reason', 'missing_operation_id'
    );
  end if;

  update public.feature_usage_events
  set
    consumed = false,
    blocked_reason = 'operation_failed',
    remaining_after = null
  where user_id = v_uid
    and feature_key = v_feature_key
    and operation_id = p_operation_id
    and consumed = true;

  get diagnostics v_updated = row_count;

  return jsonb_build_object(
    'success', true,
    'refunded', (v_updated > 0),
    'feature_key', v_feature_key,
    'operation_id', p_operation_id
  );
end;
$$;

grant select on table public.feature_usage_events to authenticated, service_role;

grant execute on function public.get_autobalance_feature_limit(text, text) to authenticated, service_role;
grant execute on function public.get_autobalance_quota_snapshot() to authenticated, service_role;
grant execute on function public.consume_autobalance_quota(text, uuid, text, jsonb) to authenticated, service_role;
grant execute on function public.release_autobalance_quota(text, uuid) to authenticated, service_role;

commit;
