-- Foundation for scalable training variants + per-equipment tracking

-- 1) Movement patterns catalog
create table if not exists public.training_movement_patterns (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text
);

create table if not exists public.exercise_movement_patterns (
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  pattern_id bigint not null references public.training_movement_patterns(id) on delete cascade,
  is_primary boolean not null default false,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  primary key (exercise_id, pattern_id)
);

-- 2) Equipment alternatives per exercise
create table if not exists public.exercise_equipment_options (
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  equipment_id bigint not null references public.equipment(id) on delete cascade,
  is_default boolean not null default false,
  priority smallint not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  primary key (exercise_id, equipment_id)
);

-- 3) User equipment inventory for availability-based alternatives
create table if not exists public.user_equipment (
  user_id uuid not null references auth.users(id) on delete cascade,
  equipment_id bigint not null references public.equipment(id) on delete cascade,
  has_access boolean not null default true,
  notes text,
  updated_at timestamptz not null default now(),
  primary key (user_id, equipment_id)
);

-- 4) Track actual apparatus used in each workout exercise
alter table public.workout_exercises
  add column if not exists performed_equipment_id bigint references public.equipment(id);

-- Backfill historical rows with exercise default equipment when available.
update public.workout_exercises we
set performed_equipment_id = e.equipment_id
from public.exercises e
where we.exercise_id = e.id
  and we.performed_equipment_id is null
  and e.equipment_id is not null;

-- 5) Enforce that logged equipment is valid for the exercise (default or alternative)
create or replace function public.validate_workout_exercise_equipment()
returns trigger
language plpgsql
as $$
declare
  v_default_equipment_id bigint;
begin
  if new.exercise_id is null then
    return new;
  end if;

  select equipment_id
  into v_default_equipment_id
  from public.exercises
  where id = new.exercise_id;

  if new.performed_equipment_id is null and v_default_equipment_id is not null then
    new.performed_equipment_id := v_default_equipment_id;
  end if;

  if new.performed_equipment_id is null then
    return new;
  end if;

  if v_default_equipment_id = new.performed_equipment_id then
    return new;
  end if;

  if exists (
    select 1
    from public.exercise_equipment_options eeo
    where eeo.exercise_id = new.exercise_id
      and eeo.equipment_id = new.performed_equipment_id
  ) then
    return new;
  end if;

  raise exception 'performed_equipment_id % is not valid for exercise_id %', new.performed_equipment_id, new.exercise_id;
end;
$$;

drop trigger if exists trg_validate_workout_exercise_equipment on public.workout_exercises;
create trigger trg_validate_workout_exercise_equipment
before insert or update of exercise_id, performed_equipment_id
on public.workout_exercises
for each row
execute function public.validate_workout_exercise_equipment();

-- 6) Indexes
create index if not exists exercise_movement_patterns_pattern_id_idx
  on public.exercise_movement_patterns(pattern_id);

create index if not exists exercise_equipment_options_equipment_id_idx
  on public.exercise_equipment_options(equipment_id);

create index if not exists workout_exercises_performed_equipment_id_idx
  on public.workout_exercises(performed_equipment_id);

create index if not exists user_equipment_equipment_id_idx
  on public.user_equipment(equipment_id);

-- 7) RLS + policies
alter table public.training_movement_patterns enable row level security;
alter table public.exercise_movement_patterns enable row level security;
alter table public.exercise_equipment_options enable row level security;
alter table public.user_equipment enable row level security;

-- Catalog read policies
create policy "Allow read to all training movement patterns"
on public.training_movement_patterns
for select using (true);

create policy "Allow read to all exercise movement patterns"
on public.exercise_movement_patterns
for select using (true);

create policy "Allow read to all exercise equipment options"
on public.exercise_equipment_options
for select using (true);

-- Admin full access policies
create policy "Allow admin full access on training movement patterns"
on public.training_movement_patterns
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

create policy "Allow admin full access on exercise movement patterns"
on public.exercise_movement_patterns
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

create policy "Allow admin full access on exercise equipment options"
on public.exercise_equipment_options
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

-- User equipment policies
create policy "Allow users to manage their own equipment"
on public.user_equipment
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Coaches can manage user equipment for clients"
on public.user_equipment
for all
using (
  exists (
    select 1
    from public.coach_clients cc
    where cc.coach_id = auth.uid()
      and cc.client_id = user_equipment.user_id
  )
)
with check (
  exists (
    select 1
    from public.coach_clients cc
    where cc.coach_id = auth.uid()
      and cc.client_id = user_equipment.user_id
  )
);

create policy "Allow admin full access on user equipment"
on public.user_equipment
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

grant all on table public.training_movement_patterns to anon, authenticated, service_role;
grant all on table public.exercise_movement_patterns to anon, authenticated, service_role;
grant all on table public.exercise_equipment_options to anon, authenticated, service_role;
grant all on table public.user_equipment to anon, authenticated, service_role;
grant all on sequence public.training_movement_patterns_id_seq to anon, authenticated, service_role;

-- 8) Seed movement patterns
insert into public.training_movement_patterns (code, name, description)
values
  ('traccion_horizontal', 'Traccion Horizontal', 'Remos y tirones horizontales'),
  ('traccion_vertical', 'Traccion Vertical', 'Dominadas y jalones verticales'),
  ('empuje_horizontal', 'Empuje Horizontal', 'Press/flexiones horizontales'),
  ('empuje_vertical', 'Empuje Vertical', 'Presses verticales y variantes'),
  ('sentadilla', 'Sentadilla', 'Patron dominante de rodilla'),
  ('bisagra_cadera', 'Bisagra de Cadera', 'Hinge y cadena posterior'),
  ('zancada_unilateral', 'Zancada Unilateral', 'Patron unilateral de pierna'),
  ('extension_rodilla', 'Extension de Rodilla', 'Trabajo dominante de cuadriceps'),
  ('flexion_rodilla', 'Flexion de Rodilla', 'Trabajo de isquios/gemelos'),
  ('core_flexion', 'Core Flexion', 'Compresion/flexion abdominal'),
  ('core_anti_extension', 'Core Anti-Extension', 'Estabilidad anti-extension'),
  ('core_anti_rotacion', 'Core Anti-Rotacion', 'Estabilidad anti-rotacion/lateral'),
  ('abduccion_aduccion_cadera', 'Abduccion/Aduccion Cadera', 'Trabajo especifico de cadera'),
  ('locomocion_cargada', 'Locomocion Cargada', 'Carries y desplazamiento con carga'),
  ('agarre', 'Agarre', 'Trabajo de agarre/antebrazo'),
  ('cardio', 'Cardio', 'Condicionamiento cardiovascular')
on conflict (code) do update
set name = excluded.name,
    description = excluded.description;

-- 9) Map exercises to primary movement patterns (heuristic + imported catalog)
with m as (
  select code, id from public.training_movement_patterns
), mapped as (
  select e.id as exercise_id,
         case
           when lower(e.name) like '%remo%' then (select id from m where code='traccion_horizontal')
           when lower(e.name) like '%dominad%' then (select id from m where code='traccion_vertical')
           when lower(e.name) like '%jalon%' then (select id from m where code='traccion_vertical')
           when lower(e.name) like '%face pull%' then (select id from m where code='traccion_horizontal')
           when lower(e.name) like '%press banca%' then (select id from m where code='empuje_horizontal')
           when lower(e.name) like '%press horizontal%' then (select id from m where code='empuje_horizontal')
           when lower(e.name) like '%flexion%' and lower(e.name) not like '%muneca%' and lower(e.name) not like '%tibial%' then (select id from m where code='empuje_horizontal')
           when lower(e.name) like '%fondo%' then (select id from m where code='empuje_horizontal')
           when lower(e.name) like '%press militar%' then (select id from m where code='empuje_vertical')
           when lower(e.name) like '%sentadilla%' and lower(e.name) not like '%sumo%' then (select id from m where code='sentadilla')
           when lower(e.name) like '%pistol squat%' then (select id from m where code='sentadilla')
           when lower(e.name) like '%prensa%' then (select id from m where code='sentadilla')
           when lower(e.name) like '%hack%' then (select id from m where code='sentadilla')
           when lower(e.name) like '%peso muerto%' then (select id from m where code='bisagra_cadera')
           when lower(e.name) like '%buenos dias%' then (select id from m where code='bisagra_cadera')
           when lower(e.name) like '%hip thrust%' then (select id from m where code='bisagra_cadera')
           when lower(e.name) like '%zancada%' or lower(e.name) like '%step up%' then (select id from m where code='zancada_unilateral')
           when lower(e.name) like '%extension de cuadriceps%' then (select id from m where code='extension_rodilla')
           when lower(e.name) like '%curl femoral%' then (select id from m where code='flexion_rodilla')
           when lower(e.name) like '%gemelo%' then (select id from m where code='flexion_rodilla')
           when lower(e.name) like '%plancha%' or lower(e.name) like '%hollow%' then (select id from m where code='core_anti_extension')
           when lower(e.name) like '%pallof%' or lower(e.name) like '%bird dog%' then (select id from m where code='core_anti_rotacion')
           when lower(e.name) like '%abs%' or lower(e.name) like '%knee raises%' then (select id from m where code='core_flexion')
           when lower(e.name) like '%abduccion%' or lower(e.name) like '%aduccion%' then (select id from m where code='abduccion_aduccion_cadera')
           when lower(e.name) like '%farmer carry%' or lower(e.name) like '%paseo del granjero%' then (select id from m where code='locomocion_cargada')
           when lower(e.name) like '%agarre%' or lower(e.name) like '%muneca%' then (select id from m where code='agarre')
           when lower(e.name) in ('comba', 'bici', 'carrera', 'escaleras') then (select id from m where code='cardio')
           else null
         end as pattern_id
  from public.exercises e
)
insert into public.exercise_movement_patterns (exercise_id, pattern_id, is_primary, source)
select exercise_id, pattern_id, true, 'seed_20260319220000'
from mapped
where pattern_id is not null
on conflict (exercise_id, pattern_id) do update
set is_primary = excluded.is_primary,
    source = excluded.source;

-- 10) Register default equipment as explicit option
insert into public.exercise_equipment_options (exercise_id, equipment_id, is_default, priority, notes)
select e.id, e.equipment_id, true, 10, 'default from exercises.equipment_id'
from public.exercises e
where e.equipment_id is not null
on conflict (exercise_id, equipment_id) do update
set is_default = excluded.is_default,
    priority = least(public.exercise_equipment_options.priority, excluded.priority),
    notes = excluded.notes;

-- 11) Pattern-based equipment alternatives
with pattern_equipment as (
  select 'traccion_horizontal'::text as pattern_code, 'polea baja'::text as equipment_name, 20::smallint as priority union all
  select 'traccion_horizontal', 'mancuernas', 30 union all
  select 'traccion_horizontal', 'barra olimpica', 40 union all
  select 'traccion_horizontal', 'aros de gimnasia', 50 union all
  select 'traccion_horizontal', 'trx', 60 union all
  select 'traccion_horizontal', 'barra baja (remo invertido)', 70 union all
  select 'traccion_horizontal', 'maquina guiada', 80 union all

  select 'traccion_vertical', 'barra alta (dominadas)', 20 union all
  select 'traccion_vertical', 'polea alta', 30 union all
  select 'traccion_vertical', 'aros de gimnasia', 40 union all
  select 'traccion_vertical', 'trx', 50 union all
  select 'traccion_vertical', 'bandas elasticas', 60 union all

  select 'empuje_horizontal', 'peso corporal', 20 union all
  select 'empuje_horizontal', 'mancuernas', 30 union all
  select 'empuje_horizontal', 'barra olimpica', 40 union all
  select 'empuje_horizontal', 'maquina guiada', 50 union all
  select 'empuje_horizontal', 'agarre bajo/paralletes', 60 union all
  select 'empuje_horizontal', 'aros de gimnasia', 70 union all
  select 'empuje_horizontal', 'bandas elasticas', 80 union all

  select 'empuje_vertical', 'mancuernas', 20 union all
  select 'empuje_vertical', 'barra olimpica', 30 union all
  select 'empuje_vertical', 'maquina guiada', 40 union all
  select 'empuje_vertical', 'bandas elasticas', 50 union all
  select 'empuje_vertical', 'peso corporal', 60 union all

  select 'sentadilla', 'peso corporal', 20 union all
  select 'sentadilla', 'mancuernas', 30 union all
  select 'sentadilla', 'kettlebell', 40 union all
  select 'sentadilla', 'barra olimpica', 50 union all
  select 'sentadilla', 'maquina guiada', 60 union all

  select 'bisagra_cadera', 'peso corporal', 20 union all
  select 'bisagra_cadera', 'mancuernas', 30 union all
  select 'bisagra_cadera', 'kettlebell', 40 union all
  select 'bisagra_cadera', 'barra olimpica', 50 union all
  select 'bisagra_cadera', 'maquina guiada', 60 union all

  select 'zancada_unilateral', 'peso corporal', 20 union all
  select 'zancada_unilateral', 'mancuernas', 30 union all
  select 'zancada_unilateral', 'kettlebell', 40 union all
  select 'zancada_unilateral', 'barra olimpica', 50 union all
  select 'zancada_unilateral', 'banco', 60 union all

  select 'extension_rodilla', 'maquina guiada', 20 union all
  select 'extension_rodilla', 'bandas elasticas', 30 union all
  select 'extension_rodilla', 'peso corporal', 40 union all

  select 'flexion_rodilla', 'maquina guiada', 20 union all
  select 'flexion_rodilla', 'tobilleras lastradas', 30 union all
  select 'flexion_rodilla', 'bandas elasticas', 40 union all
  select 'flexion_rodilla', 'peso corporal', 50 union all

  select 'core_flexion', 'peso corporal', 20 union all
  select 'core_flexion', 'maquina guiada', 30 union all
  select 'core_flexion', 'barra alta (dominadas)', 40 union all
  select 'core_flexion', 'agarre bajo/paralletes', 50 union all

  select 'core_anti_extension', 'peso corporal', 20 union all
  select 'core_anti_extension', 'aros de gimnasia', 30 union all
  select 'core_anti_extension', 'trx', 40 union all

  select 'core_anti_rotacion', 'peso corporal', 20 union all
  select 'core_anti_rotacion', 'polea baja', 30 union all
  select 'core_anti_rotacion', 'bandas elasticas', 40 union all

  select 'abduccion_aduccion_cadera', 'maquina guiada', 20 union all
  select 'abduccion_aduccion_cadera', 'bandas elasticas', 30 union all
  select 'abduccion_aduccion_cadera', 'peso corporal', 40 union all

  select 'locomocion_cargada', 'mancuernas', 20 union all
  select 'locomocion_cargada', 'kettlebell', 30 union all
  select 'locomocion_cargada', 'barra olimpica', 40 union all

  select 'agarre', 'barra alta (dominadas)', 20 union all
  select 'agarre', 'mancuernas', 30 union all
  select 'agarre', 'kettlebell', 40 union all

  select 'cardio', 'comba', 20 union all
  select 'cardio', 'bicicleta estatica', 30 union all
  select 'cardio', 'escaleras', 40 union all
  select 'cardio', 'cinta de correr', 50
)
insert into public.exercise_equipment_options (exercise_id, equipment_id, is_default, priority, notes)
select distinct emp.exercise_id,
       eq.id as equipment_id,
       false as is_default,
       pe.priority,
       format('pattern option: %s', pe.pattern_code) as notes
from public.exercise_movement_patterns emp
join public.training_movement_patterns p on p.id = emp.pattern_id and emp.is_primary
join pattern_equipment pe on pe.pattern_code = p.code
join public.equipment eq on lower(eq.name) = lower(pe.equipment_name)
on conflict (exercise_id, equipment_id) do update
set priority = least(public.exercise_equipment_options.priority, excluded.priority);

-- 12) Alternative lookup function filtered by user equipment
create or replace function public.get_exercise_alternatives(
  p_exercise_id bigint,
  p_user_id uuid default auth.uid(),
  p_only_available boolean default true,
  p_limit integer default 10
)
returns table (
  exercise_id bigint,
  exercise_name text,
  matching_patterns text[],
  equipment_options text[],
  available_equipment_options text[],
  last_workout_date date,
  last_weight integer,
  last_reps integer
)
language sql
stable
as $$
with base_patterns as (
  select pattern_id
  from public.exercise_movement_patterns
  where exercise_id = p_exercise_id
), candidates as (
  select distinct e.id, e.name
  from public.exercises e
  join public.exercise_movement_patterns emp on emp.exercise_id = e.id
  join base_patterns bp on bp.pattern_id = emp.pattern_id
  where e.id <> p_exercise_id
), candidate_patterns as (
  select c.id as exercise_id,
         array_agg(distinct p.name order by p.name) as matching_patterns
  from candidates c
  join public.exercise_movement_patterns emp on emp.exercise_id = c.id
  join base_patterns bp on bp.pattern_id = emp.pattern_id
  join public.training_movement_patterns p on p.id = emp.pattern_id
  group by c.id
), candidate_equipment as (
  select c.id as exercise_id,
         array_agg(distinct eq.name order by eq.name) as equipment_options,
         array_agg(distinct eq.name order by eq.name)
           filter (where coalesce(ue.has_access, false)) as available_equipment_options
  from candidates c
  join public.exercise_equipment_options eeo on eeo.exercise_id = c.id
  join public.equipment eq on eq.id = eeo.equipment_id
  left join public.user_equipment ue
    on ue.user_id = p_user_id
   and ue.equipment_id = eeo.equipment_id
  group by c.id
), latest_set as (
  select we.exercise_id,
         w.performed_on,
         es.weight,
         es.reps,
         row_number() over (
           partition by we.exercise_id
           order by w.performed_on desc, es.set_no desc nulls last, es.id desc
         ) as rn
  from public.workout_exercises we
  join public.workouts w on w.id = we.workout_id
  left join public.exercise_sets es on es.workout_exercise_id = we.id
  where w.user_id = p_user_id
)
select c.id as exercise_id,
       c.name as exercise_name,
       cp.matching_patterns,
       ce.equipment_options,
       ce.available_equipment_options,
       ls.performed_on as last_workout_date,
       ls.weight as last_weight,
       ls.reps as last_reps
from candidates c
join candidate_patterns cp on cp.exercise_id = c.id
join candidate_equipment ce on ce.exercise_id = c.id
left join latest_set ls on ls.exercise_id = c.id and ls.rn = 1
where (not p_only_available)
   or (coalesce(array_length(ce.available_equipment_options, 1), 0) > 0)
order by ls.performed_on desc nulls last, c.name
limit greatest(coalesce(p_limit, 10), 1);
$$;
