BEGIN;

CREATE TABLE IF NOT EXISTS public.recipe_styles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.recipe_styles OWNER TO postgres;

INSERT INTO public.recipe_styles (name, description, display_order)
VALUES
  ('Caldo', 'Preparaciones liquidas o semiliquidas', 10),
  ('Sopa', 'Sopas y cremas de cuchara', 20),
  ('Bocadillo', 'Bocadillos, sandwiches y wraps', 30),
  ('Plato combinado', 'Combinaciones completas en un plato', 40),
  ('Ensalada', 'Preparaciones frias basadas en vegetales u hojas', 50),
  ('Guiso', 'Preparaciones de coccion lenta', 60),
  ('Bowl', 'Preparaciones servidas en bowl', 70),
  ('Snack', 'Preparaciones rapidas o pequenas porciones', 80)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.recipes
  ADD COLUMN IF NOT EXISTS recipe_style_id bigint;

ALTER TABLE public.user_recipes
  ADD COLUMN IF NOT EXISTS recipe_style_id bigint;

ALTER TABLE public.diet_plan_recipes
  ADD COLUMN IF NOT EXISTS custom_recipe_style_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'recipes_recipe_style_id_fkey'
  ) THEN
    ALTER TABLE public.recipes
      ADD CONSTRAINT recipes_recipe_style_id_fkey
      FOREIGN KEY (recipe_style_id)
      REFERENCES public.recipe_styles(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'user_recipes_recipe_style_id_fkey'
  ) THEN
    ALTER TABLE public.user_recipes
      ADD CONSTRAINT user_recipes_recipe_style_id_fkey
      FOREIGN KEY (recipe_style_id)
      REFERENCES public.recipe_styles(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'diet_plan_recipes_custom_recipe_style_id_fkey'
  ) THEN
    ALTER TABLE public.diet_plan_recipes
      ADD CONSTRAINT diet_plan_recipes_custom_recipe_style_id_fkey
      FOREIGN KEY (custom_recipe_style_id)
      REFERENCES public.recipe_styles(id)
      ON DELETE SET NULL;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_recipes_recipe_style_id ON public.recipes(recipe_style_id);
CREATE INDEX IF NOT EXISTS idx_user_recipes_recipe_style_id ON public.user_recipes(recipe_style_id);
CREATE INDEX IF NOT EXISTS idx_diet_plan_recipes_custom_recipe_style_id ON public.diet_plan_recipes(custom_recipe_style_id);

-- Exponer el estilo en las vistas de compatibilidad
CREATE OR REPLACE VIEW public.free_recipes AS
SELECT
  id,
  user_id,
  created_at,
  day_meal_id,
  name,
  instructions,
  status,
  diet_plan_id,
  prep_time_min,
  difficulty,
  parent_user_recipe_id AS parent_free_recipe_id,
  parent_recipe_id,
  source_user_recipe_id AS source_free_recipe_id,
  recipe_style_id
FROM public.user_recipes
WHERE type = 'free';

CREATE OR REPLACE VIEW public.private_recipes AS
SELECT
  id,
  user_id,
  source_user_recipe_id AS source_free_recipe_id,
  name,
  instructions,
  created_at,
  diet_plan_id,
  day_meal_id,
  prep_time_min,
  difficulty,
  parent_user_recipe_id AS parent_private_recipe_id,
  recipe_style_id
FROM public.user_recipes
WHERE type = 'private';

ALTER VIEW public.free_recipes OWNER TO postgres;
ALTER VIEW public.private_recipes OWNER TO postgres;

-- Ajustar RPCs para copiar/guardar recipe_style_id
CREATE OR REPLACE FUNCTION public.approve_free_recipe_as_global(
  p_free_recipe_id bigint,
  p_recipe_data jsonb,
  p_ingredients jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_user_id uuid;
  v_day_meal_id bigint;
  v_diet_plan_id bigint;
  v_original_recipe_style_id bigint;
  v_recipe_style_id bigint;
  new_recipe_id bigint;
  new_diet_plan_recipe_id bigint;
  ingredient_record jsonb;
  occurrence_record record;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Only admins can perform this action';
  END IF;

  SELECT user_id, diet_plan_id, day_meal_id, recipe_style_id
  INTO v_user_id, v_diet_plan_id, v_day_meal_id, v_original_recipe_style_id
  FROM user_recipes
  WHERE id = p_free_recipe_id;

  v_recipe_style_id := NULLIF(p_recipe_data->>'recipe_style_id', '')::bigint;
  IF v_recipe_style_id IS NULL THEN
    v_recipe_style_id := v_original_recipe_style_id;
  END IF;

  INSERT INTO recipes (name, instructions, prep_time_min, difficulty, recipe_style_id, created_by)
  VALUES (
    p_recipe_data->>'name',
    p_recipe_data->>'instructions',
    (p_recipe_data->>'prep_time_min')::integer,
    p_recipe_data->>'difficulty',
    v_recipe_style_id,
    auth.uid()
  )
  RETURNING id INTO new_recipe_id;

  FOR ingredient_record IN SELECT * FROM jsonb_array_elements(p_ingredients)
  LOOP
    INSERT INTO recipe_ingredients (recipe_id, food_id, grams, food_group_id)
    VALUES (
      new_recipe_id,
      (ingredient_record->>'food_id')::bigint,
      (ingredient_record->>'grams')::integer,
      (ingredient_record->>'food_group_id')::bigint
    );
  END LOOP;

  IF v_diet_plan_id IS NOT NULL THEN
    INSERT INTO diet_plan_recipes (
      diet_plan_id, recipe_id, day_meal_id, is_customized,
      custom_name, custom_instructions, custom_prep_time_min, custom_difficulty
    )
    VALUES (
      v_diet_plan_id, new_recipe_id, v_day_meal_id, true,
      p_recipe_data->>'name',
      p_recipe_data->>'instructions',
      (p_recipe_data->>'prep_time_min')::integer,
      p_recipe_data->>'difficulty'
    )
    RETURNING id INTO new_diet_plan_recipe_id;

    FOR ingredient_record IN SELECT * FROM jsonb_array_elements(p_ingredients)
    LOOP
      INSERT INTO recipe_ingredients (diet_plan_recipe_id, food_id, grams)
      VALUES (
        new_diet_plan_recipe_id,
        (ingredient_record->>'food_id')::bigint,
        (ingredient_record->>'grams')::integer
      );
    END LOOP;

    FOR occurrence_record IN
      SELECT id FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id
    LOOP
      UPDATE daily_meal_logs
      SET
        diet_plan_recipe_id = new_diet_plan_recipe_id,
        free_recipe_occurrence_id = NULL
      WHERE free_recipe_occurrence_id = occurrence_record.id;
    END LOOP;

    UPDATE equivalence_adjustments
    SET
      source_diet_plan_recipe_id = new_diet_plan_recipe_id,
      source_user_recipe_id = NULL
    WHERE source_user_recipe_id = p_free_recipe_id;

    DELETE FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id;
    DELETE FROM recipe_ingredients WHERE user_recipe_id = p_free_recipe_id;
    UPDATE user_recipes SET source_user_recipe_id = NULL WHERE source_user_recipe_id = p_free_recipe_id;
    DELETE FROM user_recipes WHERE id = p_free_recipe_id;

    RETURN jsonb_build_object('success', true, 'recipeId', new_recipe_id, 'addedToPlan', true);
  ELSE
    RETURN jsonb_build_object('success', true, 'recipeId', new_recipe_id, 'addedToPlan', false, 'reason', 'No diet plan ID found on free recipe');
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

CREATE OR REPLACE FUNCTION public.convert_free_to_private_recipe(
  p_free_recipe_id bigint,
  p_new_recipe_data jsonb,
  p_new_ingredients jsonb
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_user_id uuid;
  v_diet_plan_id bigint;
  v_day_meal_id bigint;
  v_original_recipe_style_id bigint;
  v_recipe_style_id bigint;
  new_user_recipe_id bigint;
  occurrence_record record;
  ingredient_record jsonb;
  is_coach boolean;
  is_admin_user boolean;
BEGIN
  is_admin_user := is_admin();
  is_coach := EXISTS (
    SELECT 1 FROM user_roles ur
    JOIN roles r ON ur.role_id = r.id
    WHERE ur.user_id = auth.uid() AND r.role = 'coach'
  );

  SELECT user_id, diet_plan_id, day_meal_id, recipe_style_id
  INTO v_user_id, v_diet_plan_id, v_day_meal_id, v_original_recipe_style_id
  FROM user_recipes
  WHERE id = p_free_recipe_id;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Free recipe not found';
  END IF;

  IF NOT is_admin_user THEN
    IF is_coach THEN
      IF NOT EXISTS (SELECT 1 FROM coach_clients WHERE coach_id = auth.uid() AND client_id = v_user_id) THEN
        RAISE EXCEPTION 'Permission denied: Client is not assigned to you.';
      END IF;
    ELSE
      RAISE EXCEPTION 'Only admins or assigned coaches can perform this action';
    END IF;
  END IF;

  v_recipe_style_id := NULLIF(p_new_recipe_data->>'recipe_style_id', '')::bigint;
  IF v_recipe_style_id IS NULL THEN
    v_recipe_style_id := v_original_recipe_style_id;
  END IF;

  INSERT INTO user_recipes (
    user_id, type, name, instructions, prep_time_min, difficulty,
    recipe_style_id, diet_plan_id, day_meal_id, source_user_recipe_id
  )
  VALUES (
    v_user_id,
    'private',
    p_new_recipe_data->>'name',
    p_new_recipe_data->>'instructions',
    (p_new_recipe_data->>'prep_time_min')::integer,
    p_new_recipe_data->>'difficulty',
    v_recipe_style_id,
    v_diet_plan_id,
    v_day_meal_id,
    p_free_recipe_id
  )
  RETURNING id INTO new_user_recipe_id;

  FOR ingredient_record IN SELECT * FROM jsonb_array_elements(p_new_ingredients)
  LOOP
    INSERT INTO recipe_ingredients (user_recipe_id, food_id, grams)
    VALUES (
      new_user_recipe_id,
      (ingredient_record->>'food_id')::bigint,
      (ingredient_record->>'grams')::numeric
    );
  END LOOP;

  FOR occurrence_record IN
    SELECT id FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id
  LOOP
    UPDATE daily_meal_logs
    SET
      user_recipe_id = new_user_recipe_id,
      free_recipe_occurrence_id = NULL
    WHERE free_recipe_occurrence_id = occurrence_record.id;
  END LOOP;

  UPDATE equivalence_adjustments
  SET source_user_recipe_id = new_user_recipe_id
  WHERE source_user_recipe_id = p_free_recipe_id;

  DELETE FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id;
  DELETE FROM recipe_ingredients WHERE user_recipe_id = p_free_recipe_id;
  DELETE FROM user_recipes WHERE id = p_free_recipe_id;

  RETURN new_user_recipe_id;
END;
$$;

ALTER TABLE public.recipe_styles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated read access on recipe_styles" ON public.recipe_styles;
CREATE POLICY "Allow authenticated read access on recipe_styles"
ON public.recipe_styles
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow admin full access on recipe_styles" ON public.recipe_styles;
CREATE POLICY "Allow admin full access on recipe_styles"
ON public.recipe_styles
USING (is_admin())
WITH CHECK (is_admin());

GRANT ALL ON TABLE public.recipe_styles TO anon;
GRANT ALL ON TABLE public.recipe_styles TO authenticated;
GRANT ALL ON TABLE public.recipe_styles TO service_role;
GRANT ALL ON SEQUENCE public.recipe_styles_id_seq TO anon;
GRANT ALL ON SEQUENCE public.recipe_styles_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.recipe_styles_id_seq TO service_role;

COMMIT;
