-- Phase 1: Dynamic pricing model + manual subscription grants by admin

-- 1) Roles metadata
alter table public.roles
  add column if not exists description text;

-- 2) Commercial plans managed by admin and consumed by Home/Pricing
create table if not exists public.commercial_plans (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  subtitle text,
  description text,
  price_amount numeric(10,2) not null default 0,
  price_currency text not null default 'EUR',
  billing_type text not null default 'monthly' check (billing_type in ('monthly', 'one_time')),
  cta_label text not null default 'Empezar',
  cta_link text,
  is_popular boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  show_on_home boolean not null default true,
  show_on_pricing boolean not null default true,
  created_by uuid,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_commercial_plans_active_sort
  on public.commercial_plans (is_active, sort_order, id);

create table if not exists public.commercial_plan_features (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.commercial_plans(id) on delete cascade,
  feature_text text not null,
  included boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_commercial_plan_features_plan_sort
  on public.commercial_plan_features (plan_id, sort_order, id);

create table if not exists public.commercial_plan_role_targets (
  plan_id bigint not null references public.commercial_plans(id) on delete cascade,
  role_id integer not null references public.roles(id),
  primary key (plan_id, role_id)
);

-- 3) User subscriptions/access grants
create table if not exists public.user_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id bigint not null references public.commercial_plans(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'canceled', 'expired', 'pending')),
  source text not null default 'manual' check (source in ('manual', 'stripe', 'coach')),
  is_complimentary boolean not null default false,
  amount_paid numeric(10,2),
  currency text not null default 'EUR',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  notes text,
  assigned_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_subscriptions_user_status
  on public.user_subscriptions (user_id, status, starts_at desc);

create index if not exists idx_user_subscriptions_plan
  on public.user_subscriptions (plan_id);

-- 4) updated_at triggers
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Attach only if not already attached
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_commercial_plans_updated_at'
  ) THEN
    CREATE TRIGGER trg_commercial_plans_updated_at
    BEFORE UPDATE ON public.commercial_plans
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_commercial_plan_features_updated_at'
  ) THEN
    CREATE TRIGGER trg_commercial_plan_features_updated_at
    BEFORE UPDATE ON public.commercial_plan_features
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_user_subscriptions_updated_at'
  ) THEN
    CREATE TRIGGER trg_user_subscriptions_updated_at
    BEFORE UPDATE ON public.user_subscriptions
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END
$$;

-- 5) Role/access synchronization helpers
create or replace function public.sync_user_role_from_subscription(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_client_role_id integer;
  v_free_role_id integer;
  v_has_active_client_access boolean;
begin
  select id into v_client_role_id from public.roles where role = 'client' limit 1;
  select id into v_free_role_id from public.roles where role = 'free' limit 1;

  if v_client_role_id is null or v_free_role_id is null then
    raise exception 'Required roles (client/free) are missing in public.roles';
  end if;

  select exists (
    select 1
    from public.user_subscriptions us
    join public.commercial_plan_role_targets rt on rt.plan_id = us.plan_id
    join public.roles r on r.id = rt.role_id
    where us.user_id = p_user_id
      and us.status = 'active'
      and (us.ends_at is null or us.ends_at > now())
      and r.role = 'client'
  ) into v_has_active_client_access;

  if v_has_active_client_access then
    insert into public.user_roles (user_id, role_id)
    values (p_user_id, v_client_role_id)
    on conflict (user_id) do update
      set role_id = excluded.role_id;
  else
    insert into public.user_roles (user_id, role_id)
    values (p_user_id, v_free_role_id)
    on conflict (user_id) do update
      set role_id = excluded.role_id;
  end if;
end;
$$;

create or replace function public.admin_upsert_user_subscription(
  p_user_id uuid,
  p_plan_id bigint,
  p_status text default 'active',
  p_source text default 'manual',
  p_is_complimentary boolean default true,
  p_amount_paid numeric default null,
  p_currency text default 'EUR',
  p_starts_at timestamptz default now(),
  p_ends_at timestamptz default null,
  p_notes text default null,
  p_sync_role boolean default true
)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_sub_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only admins can manage subscriptions';
  end if;

  insert into public.user_subscriptions (
    user_id,
    plan_id,
    status,
    source,
    is_complimentary,
    amount_paid,
    currency,
    starts_at,
    ends_at,
    notes,
    assigned_by
  ) values (
    p_user_id,
    p_plan_id,
    p_status,
    p_source,
    p_is_complimentary,
    p_amount_paid,
    coalesce(p_currency, 'EUR'),
    coalesce(p_starts_at, now()),
    p_ends_at,
    p_notes,
    auth.uid()
  )
  returning id into v_sub_id;

  if p_sync_role then
    perform public.sync_user_role_from_subscription(p_user_id);
  end if;

  return v_sub_id;
end;
$$;

-- 6) Seed defaults if missing
insert into public.commercial_plans (
  slug, name, subtitle, description, price_amount, price_currency, billing_type,
  cta_label, cta_link, is_popular, is_active, sort_order, show_on_home, show_on_pricing
)
select * from (
  values
    ('free', 'Free', 'Para empezar', 'Para empezar a usar Bibofit de forma manual.', 0, 'EUR', 'monthly', 'Empezar Gratis', '/signup', false, true, 1, true, true),
    ('pro', 'Pro', 'Automatiza tu nutrición', 'Automatiza tu nutrición con todas las ventajas.', 15, 'EUR', 'monthly', 'Prueba Gratis 15 días', '/signup', true, true, 2, true, true),
    ('coaching', 'Asesoría', 'Soporte profesional', 'Soporte profesional para garantizar resultados.', 35, 'EUR', 'monthly', 'Contactar', '/contact', false, true, 3, true, true)
) as v(slug, name, subtitle, description, price_amount, price_currency, billing_type, cta_label, cta_link, is_popular, is_active, sort_order, show_on_home, show_on_pricing)
where not exists (select 1 from public.commercial_plans cp where cp.slug = v.slug);

-- Replace features for seeded plans to keep deterministic baseline
with seed_features as (
  select 'free'::text as plan_slug, 1 as sort_order, 'Asignación de 1 plantilla de Dieta'::text as feature_text, true as included union all
  select 'free', 2, 'Registro de Peso y Progreso', true union all
  select 'free', 3, 'Recetas Libres y Picoteos', true union all
  select 'free', 4, 'Lista de la Compra Inteligente', true union all
  select 'free', 5, 'Autocuadre de Macros', false union all
  select 'free', 6, 'Soporte Prioritario', false union all

  select 'pro', 1, 'Todo lo incluido en Free', true union all
  select 'pro', 2, 'Asignación ilimitada de plantillas', true union all
  select 'pro', 3, 'Autocuadre Automático de Dietas', true union all
  select 'pro', 4, 'Actualización dinámica de macros', true union all
  select 'pro', 5, 'Chat integrado con soporte básico', true union all
  select 'pro', 6, 'Análisis avanzado de progreso', true union all

  select 'coaching', 1, 'Todo lo incluido en Pro', true union all
  select 'coaching', 2, 'Asignación directa a un Dietista', true union all
  select 'coaching', 3, 'Contacto 1 a 1 y revisión personal', true union all
  select 'coaching', 4, 'Seguimiento semanal detallado', true union all
  select 'coaching', 5, 'Soporte Prioritario 24/7', true union all
  select 'coaching', 6, 'Ajustes ilimitados de plan', true
),
plan_ids as (
  select id, slug from public.commercial_plans where slug in ('free', 'pro', 'coaching')
)
delete from public.commercial_plan_features f
using plan_ids p
where f.plan_id = p.id;

insert into public.commercial_plan_features (plan_id, feature_text, included, sort_order)
with seed_features as (
  select 'free'::text as plan_slug, 1 as sort_order, 'Asignación de 1 plantilla de Dieta'::text as feature_text, true as included union all
  select 'free', 2, 'Registro de Peso y Progreso', true union all
  select 'free', 3, 'Recetas Libres y Picoteos', true union all
  select 'free', 4, 'Lista de la Compra Inteligente', true union all
  select 'free', 5, 'Autocuadre de Macros', false union all
  select 'free', 6, 'Soporte Prioritario', false union all

  select 'pro', 1, 'Todo lo incluido en Free', true union all
  select 'pro', 2, 'Asignación ilimitada de plantillas', true union all
  select 'pro', 3, 'Autocuadre Automático de Dietas', true union all
  select 'pro', 4, 'Actualización dinámica de macros', true union all
  select 'pro', 5, 'Chat integrado con soporte básico', true union all
  select 'pro', 6, 'Análisis avanzado de progreso', true union all

  select 'coaching', 1, 'Todo lo incluido en Pro', true union all
  select 'coaching', 2, 'Asignación directa a un Dietista', true union all
  select 'coaching', 3, 'Contacto 1 a 1 y revisión personal', true union all
  select 'coaching', 4, 'Seguimiento semanal detallado', true union all
  select 'coaching', 5, 'Soporte Prioritario 24/7', true union all
  select 'coaching', 6, 'Ajustes ilimitados de plan', true
)
select p.id, sf.feature_text, sf.included, sf.sort_order
from seed_features sf
join public.commercial_plans p on p.slug = sf.plan_slug;

-- Targets: free->free, pro/coaching->client
insert into public.commercial_plan_role_targets (plan_id, role_id)
select p.id, r.id
from public.commercial_plans p
join public.roles r on (
  (p.slug = 'free' and r.role = 'free')
  or (p.slug in ('pro', 'coaching') and r.role = 'client')
)
on conflict (plan_id, role_id) do nothing;

-- 7) RLS
alter table public.commercial_plans enable row level security;
alter table public.commercial_plan_features enable row level security;
alter table public.commercial_plan_role_targets enable row level security;
alter table public.user_subscriptions enable row level security;

-- public read for active plans and linked entities
create policy "Public read active commercial plans"
on public.commercial_plans
for select
using (is_active = true);

create policy "Public read commercial features"
on public.commercial_plan_features
for select
using (exists (
  select 1
  from public.commercial_plans p
  where p.id = commercial_plan_features.plan_id
    and p.is_active = true
));

create policy "Public read commercial plan targets"
on public.commercial_plan_role_targets
for select
using (exists (
  select 1
  from public.commercial_plans p
  where p.id = commercial_plan_role_targets.plan_id
    and p.is_active = true
));

-- admin manage policies
create policy "Admin full access commercial plans"
on public.commercial_plans
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admin full access commercial plan features"
on public.commercial_plan_features
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admin full access commercial plan role targets"
on public.commercial_plan_role_targets
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admin full access user subscriptions"
on public.user_subscriptions
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Users can read own subscriptions"
on public.user_subscriptions
for select
using (auth.uid() = user_id);

-- 8) Grants
grant all on table public.commercial_plans to anon, authenticated, service_role;
grant all on table public.commercial_plan_features to anon, authenticated, service_role;
grant all on table public.commercial_plan_role_targets to anon, authenticated, service_role;
grant all on table public.user_subscriptions to anon, authenticated, service_role;

grant all on sequence public.commercial_plans_id_seq to anon, authenticated, service_role;
grant all on sequence public.commercial_plan_features_id_seq to anon, authenticated, service_role;
grant all on sequence public.user_subscriptions_id_seq to anon, authenticated, service_role;

grant all on function public.sync_user_role_from_subscription(uuid) to authenticated, service_role;
grant all on function public.admin_upsert_user_subscription(uuid, bigint, text, text, boolean, numeric, text, timestamptz, timestamptz, text, boolean) to authenticated, service_role;
