-- Objectives catalog + multi-block day structure for mesocycle creation flow

-- 1) Objectives catalog
create table if not exists public.training_objectives (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  description text,
  is_active boolean not null default true,
  display_order integer not null default 100,
  created_at timestamptz not null default now()
);

insert into public.training_objectives (code, name, description, display_order)
values
  ('hypertrophy', 'Ganancia de masa muscular', 'Enfoque en aumentar volumen de trabajo y progresar en repeticiones/carga.', 10),
  ('cardio', 'Mejora del cardio', 'Enfoque en capacidad cardiovascular, tolerancia al esfuerzo y recuperación.', 20),
  ('strength', 'Ganancia de fuerza', 'Enfoque en progresión de carga y mejora de rendimiento en patrones principales.', 30)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    display_order = excluded.display_order,
    is_active = true;

alter table public.training_objectives enable row level security;

drop policy if exists "Allow read to all training objectives" on public.training_objectives;
create policy "Allow read to all training objectives"
on public.training_objectives
for select
using (true);

drop policy if exists "Allow admin full access on training objectives" on public.training_objectives;
create policy "Allow admin full access on training objectives"
on public.training_objectives
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

grant all on table public.training_objectives to anon, authenticated, service_role;
grant all on sequence public.training_objectives_id_seq to anon, authenticated, service_role;

-- 2) Attach objective to mesocycle
alter table public.mesocycles
  add column if not exists objective_id bigint references public.training_objectives(id);

create index if not exists mesocycles_objective_id_idx
  on public.mesocycles (objective_id);

-- Backfill objective_id from legacy objective text where possible.
update public.mesocycles m
set objective_id = t.id
from public.training_objectives t
where m.objective_id is null
  and (
    (t.code = 'hypertrophy' and lower(coalesce(m.objective, '')) ~ '(masa|hipertrof|muscul)')
    or (t.code = 'cardio' and lower(coalesce(m.objective, '')) ~ '(cardio|resistenc|aerob)')
    or (t.code = 'strength' and lower(coalesce(m.objective, '')) ~ '(fuerza|strength)')
  );

update public.mesocycles m
set objective = t.name
from public.training_objectives t
where m.objective_id = t.id
  and coalesce(trim(m.objective), '') = '';

-- 3) Multiple focus blocks inside one training day/routine
create table if not exists public.routine_day_blocks (
  id bigint generated by default as identity primary key,
  routine_id bigint not null references public.routines(id) on delete cascade,
  block_order integer not null,
  block_type text not null,
  block_label text,
  created_at timestamptz not null default now(),
  unique (routine_id, block_order)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_day_blocks_block_order_check'
      and conrelid = 'public.routine_day_blocks'::regclass
  ) then
    alter table public.routine_day_blocks
      add constraint routine_day_blocks_block_order_check
      check (block_order >= 1);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_day_blocks_block_type_check'
      and conrelid = 'public.routine_day_blocks'::regclass
  ) then
    alter table public.routine_day_blocks
      add constraint routine_day_blocks_block_type_check
      check (
        block_type in (
          'torso','pierna','fullbody','push','pull','upper','lower','core','cardio','movilidad','custom'
        )
      );
  end if;
end
$$;

create index if not exists routine_day_blocks_routine_idx
  on public.routine_day_blocks (routine_id, block_order);

alter table public.routine_day_blocks enable row level security;

drop policy if exists "Allow admin full access on routine_day_blocks" on public.routine_day_blocks;
create policy "Allow admin full access on routine_day_blocks"
on public.routine_day_blocks
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage their own routine_day_blocks" on public.routine_day_blocks;
create policy "Allow users to manage their own routine_day_blocks"
on public.routine_day_blocks
for all
using (
  exists (
    select 1
    from public.routines r
    where r.id = routine_day_blocks.routine_id
      and r.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.routines r
    where r.id = routine_day_blocks.routine_id
      and r.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view routine_day_blocks for clients" on public.routine_day_blocks;
create policy "Coaches can view routine_day_blocks for clients"
on public.routine_day_blocks
for select
using (
  exists (
    select 1
    from public.routines r
    join public.coach_clients cc on cc.client_id = r.user_id
    where r.id = routine_day_blocks.routine_id
      and cc.coach_id = auth.uid()
  )
);

grant all on table public.routine_day_blocks to anon, authenticated, service_role;
grant all on sequence public.routine_day_blocks_id_seq to anon, authenticated, service_role;

-- 4) One-shot creator for beta mesocycle builder
create or replace function public.create_mesocycle_blueprint(
  p_name text,
  p_start_date date,
  p_end_date date,
  p_objective_id bigint,
  p_days jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mesocycle_id bigint;
  v_objective_name text;
  v_day jsonb;
  v_day_idx integer := 0;
  v_routine_id bigint;
  v_day_name text;
  v_primary_type text;
  v_focuses text[];
  v_block jsonb;
  v_block_idx integer;
  v_block_type text;
  v_block_label text;
begin
  if auth.uid() is null then
    raise exception 'auth required';
  end if;

  if p_days is null or jsonb_typeof(p_days) <> 'array' or jsonb_array_length(p_days) is null or jsonb_array_length(p_days) = 0 then
    raise exception 'p_days must be a non-empty json array';
  end if;

  if jsonb_array_length(p_days) > 7 then
    raise exception 'p_days cannot exceed 7 entries';
  end if;

  if p_start_date is not null and p_end_date is not null and p_end_date < p_start_date then
    raise exception 'end_date cannot be before start_date';
  end if;

  select name
  into v_objective_name
  from public.training_objectives
  where id = p_objective_id
    and is_active;

  if v_objective_name is null then
    raise exception 'invalid p_objective_id %', p_objective_id;
  end if;

  insert into public.mesocycles (
    user_id,
    name,
    objective,
    objective_id,
    start_date,
    end_date,
    sessions_per_week
  )
  values (
    auth.uid(),
    nullif(trim(coalesce(p_name, '')), ''),
    v_objective_name,
    p_objective_id,
    p_start_date,
    p_end_date,
    jsonb_array_length(p_days)
  )
  returning id into v_mesocycle_id;

  for v_day in
    select value from jsonb_array_elements(p_days)
  loop
    v_day_idx := v_day_idx + 1;
    v_day_name := nullif(trim(coalesce(v_day->>'name', '')), '');
    v_primary_type := lower(trim(coalesce(v_day->>'primary_type', '')));

    if v_primary_type = '' then
      v_primary_type := null;
    end if;

    if v_primary_type is not null
      and v_primary_type not in ('torso','pierna','fullbody','push','pull','upper','lower','core','cardio','movilidad','custom') then
      v_primary_type := 'custom';
    end if;

    if v_day ? 'blocks'
      and jsonb_typeof(v_day->'blocks') = 'array'
      and jsonb_array_length(v_day->'blocks') > 0 then
      v_focuses := array(
        select distinct block_type
        from (
          select lower(trim(coalesce(block_item->>'type', ''))) as block_type
          from jsonb_array_elements(v_day->'blocks') block_item
        ) z
        where block_type in ('torso','pierna','fullbody','push','pull','upper','lower','core','cardio','movilidad','custom')
      );

      if coalesce(array_length(v_focuses, 1), 0) = 0 then
        v_focuses := array['custom'];
      end if;

      if v_primary_type is null then
        v_primary_type := v_focuses[1];
      end if;
    else
      if v_primary_type is null then
        v_primary_type := 'custom';
      end if;
      v_focuses := array[v_primary_type];
    end if;

    insert into public.routines (
      user_id,
      mesocycle_id,
      day_index,
      day_type,
      name,
      focus
    )
    values (
      auth.uid(),
      v_mesocycle_id,
      v_day_idx,
      v_primary_type,
      coalesce(v_day_name, initcap(v_primary_type) || ' D' || v_day_idx::text),
      array_to_string(v_focuses, ', ')
    )
    returning id into v_routine_id;

    if v_day ? 'blocks'
      and jsonb_typeof(v_day->'blocks') = 'array'
      and jsonb_array_length(v_day->'blocks') > 0 then
      v_block_idx := 0;
      for v_block in
        select value from jsonb_array_elements(v_day->'blocks')
      loop
        v_block_idx := v_block_idx + 1;
        v_block_type := lower(trim(coalesce(v_block->>'type', '')));
        if v_block_type = ''
          or v_block_type not in ('torso','pierna','fullbody','push','pull','upper','lower','core','cardio','movilidad','custom') then
          v_block_type := 'custom';
        end if;

        v_block_label := nullif(trim(coalesce(v_block->>'label', '')), '');

        insert into public.routine_day_blocks (routine_id, block_order, block_type, block_label)
        values (v_routine_id, v_block_idx, v_block_type, v_block_label);
      end loop;
    else
      insert into public.routine_day_blocks (routine_id, block_order, block_type, block_label)
      values (v_routine_id, 1, v_primary_type, null);
    end if;
  end loop;

  return v_mesocycle_id;
end;
$$;

grant execute on function public.create_mesocycle_blueprint(text,date,date,bigint,jsonb) to anon, authenticated, service_role;
