-- Persistent PR engine for training visualization/history.
-- Stores real PR events (weight/reps/e1rm) per workout exercise,
-- keeps them in sync when exercise_sets are updated,
-- and exposes PR counts in timeline RPCs.

create table if not exists public.training_pr_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  workout_exercise_id bigint not null references public.workout_exercises(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id),
  performed_on date not null,
  metric text not null,
  current_value numeric(10,2) not null,
  previous_value numeric(10,2),
  improvement_value numeric(10,2) not null,
  is_key_exercise boolean not null default false,
  created_at timestamptz not null default now(),
  unique (workout_id, workout_exercise_id, metric),
  check (metric in ('weight', 'reps', 'e1rm')),
  check (current_value >= 0),
  check (previous_value is null or previous_value >= 0),
  check (improvement_value > 0)
);

create index if not exists training_pr_events_user_date_idx
  on public.training_pr_events (user_id, performed_on desc);

create index if not exists training_pr_events_workout_idx
  on public.training_pr_events (workout_id);

create index if not exists training_pr_events_exercise_metric_idx
  on public.training_pr_events (user_id, exercise_id, metric, performed_on desc);

alter table public.training_pr_events enable row level security;

drop policy if exists "Allow admin full access on training_pr_events" on public.training_pr_events;
create policy "Allow admin full access on training_pr_events"
on public.training_pr_events
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to read own training_pr_events" on public.training_pr_events;
create policy "Allow users to read own training_pr_events"
on public.training_pr_events
for select
using (training_pr_events.user_id = auth.uid());

drop policy if exists "Coaches can view client training_pr_events" on public.training_pr_events;
create policy "Coaches can view client training_pr_events"
on public.training_pr_events
for select
using (
  exists (
    select 1
    from public.coach_clients cc
    where cc.client_id = training_pr_events.user_id
      and cc.coach_id = auth.uid()
  )
);

create or replace function public.training_refresh_workout_prs(
  p_workout_id bigint
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_user_id uuid;
  v_inserted integer := 0;
begin
  if p_workout_id is null then
    raise exception 'p_workout_id is required';
  end if;

  select w.user_id
  into v_owner_user_id
  from public.workouts w
  where w.id = p_workout_id;

  if v_owner_user_id is null then
    raise exception 'workout_id % not found', p_workout_id;
  end if;

  if not public.training_can_manage_user(v_owner_user_id) then
    raise exception 'not allowed to refresh PRs for user %', v_owner_user_id;
  end if;

  delete from public.training_pr_events tpe
  where tpe.workout_id = p_workout_id;

  with current_exercises as (
    select
      w.user_id,
      w.id as workout_id,
      w.performed_on,
      we.id as workout_exercise_id,
      we.exercise_id,
      we.performed_equipment_id,
      coalesce(tbe.is_key_exercise, false) as is_key_exercise,
      max(case when es.weight is not null and es.weight > 0 then es.weight::numeric end) as current_weight,
      max(case when es.reps is not null and es.reps > 0 then es.reps::numeric end) as current_reps,
      max(
        case
          when es.weight is not null and es.weight > 0 and es.reps is not null and es.reps > 0
            then round((es.weight::numeric * (1 + (es.reps::numeric / 30.0)))::numeric, 2)
          else null
        end
      ) as current_e1rm
    from public.workout_exercises we
    join public.workouts w on w.id = we.workout_id
    left join public.training_block_exercises tbe on tbe.id = we.training_block_exercise_id
    left join public.exercise_sets es on es.workout_exercise_id = we.id
    where w.id = p_workout_id
    group by
      w.user_id,
      w.id,
      w.performed_on,
      we.id,
      we.exercise_id,
      we.performed_equipment_id,
      coalesce(tbe.is_key_exercise, false)
  ), with_previous as (
    select
      ce.*,
      (
        select max(es_prev.weight)::numeric
        from public.workout_exercises we_prev
        join public.workouts w_prev on w_prev.id = we_prev.workout_id
        join public.exercise_sets es_prev on es_prev.workout_exercise_id = we_prev.id
        where w_prev.user_id = ce.user_id
          and we_prev.exercise_id = ce.exercise_id
          and we_prev.performed_equipment_id is not distinct from ce.performed_equipment_id
          and (w_prev.performed_on < ce.performed_on or (w_prev.performed_on = ce.performed_on and w_prev.id < ce.workout_id))
          and es_prev.weight is not null
          and es_prev.weight > 0
      ) as previous_weight,
      (
        select max(es_prev.reps)::numeric
        from public.workout_exercises we_prev
        join public.workouts w_prev on w_prev.id = we_prev.workout_id
        join public.exercise_sets es_prev on es_prev.workout_exercise_id = we_prev.id
        where w_prev.user_id = ce.user_id
          and we_prev.exercise_id = ce.exercise_id
          and we_prev.performed_equipment_id is not distinct from ce.performed_equipment_id
          and (w_prev.performed_on < ce.performed_on or (w_prev.performed_on = ce.performed_on and w_prev.id < ce.workout_id))
          and es_prev.reps is not null
          and es_prev.reps > 0
      ) as previous_reps,
      (
        select max(round((es_prev.weight::numeric * (1 + (es_prev.reps::numeric / 30.0)))::numeric, 2))
        from public.workout_exercises we_prev
        join public.workouts w_prev on w_prev.id = we_prev.workout_id
        join public.exercise_sets es_prev on es_prev.workout_exercise_id = we_prev.id
        where w_prev.user_id = ce.user_id
          and we_prev.exercise_id = ce.exercise_id
          and we_prev.performed_equipment_id is not distinct from ce.performed_equipment_id
          and (w_prev.performed_on < ce.performed_on or (w_prev.performed_on = ce.performed_on and w_prev.id < ce.workout_id))
          and es_prev.weight is not null
          and es_prev.weight > 0
          and es_prev.reps is not null
          and es_prev.reps > 0
      ) as previous_e1rm
    from current_exercises ce
  ), inserted as (
    insert into public.training_pr_events (
      user_id,
      workout_id,
      workout_exercise_id,
      exercise_id,
      performed_on,
      metric,
      current_value,
      previous_value,
      improvement_value,
      is_key_exercise
    )
    select
      wp.user_id,
      wp.workout_id,
      wp.workout_exercise_id,
      wp.exercise_id,
      wp.performed_on,
      pr.metric,
      pr.current_value,
      pr.previous_value,
      (pr.current_value - coalesce(pr.previous_value, 0))::numeric(10,2) as improvement_value,
      wp.is_key_exercise
    from with_previous wp
    cross join lateral (
      values
        ('weight'::text, wp.current_weight, wp.previous_weight),
        ('reps'::text, wp.current_reps, wp.previous_reps),
        ('e1rm'::text, wp.current_e1rm, wp.previous_e1rm)
    ) as pr(metric, current_value, previous_value)
    where pr.current_value is not null
      and (pr.previous_value is null or pr.current_value > pr.previous_value)
    returning 1
  )
  select count(*)::integer
  into v_inserted
  from inserted;

  return coalesce(v_inserted, 0);
end;
$$;

create or replace function public.training_refresh_workout_prs_by_workout_exercise(
  p_workout_exercise_id bigint
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workout_id bigint;
begin
  if p_workout_exercise_id is null then
    return 0;
  end if;

  select we.workout_id
  into v_workout_id
  from public.workout_exercises we
  where we.id = p_workout_exercise_id;

  if v_workout_id is null then
    return 0;
  end if;

  return public.training_refresh_workout_prs(v_workout_id);
end;
$$;

create or replace function public.training_refresh_prs_on_exercise_set_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workout_exercise_id bigint;
begin
  v_workout_exercise_id := coalesce(new.workout_exercise_id, old.workout_exercise_id);

  if v_workout_exercise_id is not null then
    perform public.training_refresh_workout_prs_by_workout_exercise(v_workout_exercise_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_training_refresh_prs_on_exercise_set_write on public.exercise_sets;
create trigger trg_training_refresh_prs_on_exercise_set_write
after update of reps, weight, completed_at or delete
on public.exercise_sets
for each row
execute function public.training_refresh_prs_on_exercise_set_write();

create or replace function public.training_get_pr_events(
  p_user_id uuid default auth.uid(),
  p_start_date date default current_date - 6,
  p_end_date date default current_date
)
returns table (
  event_date date,
  pr_count integer,
  key_pr_count integer,
  distinct_exercises integer
)
language sql
security definer
stable
set search_path = public
as $$
  with target_user as (
    select coalesce(p_user_id, auth.uid()) as user_id
  ), bounds as (
    select
      least(coalesce(p_start_date, current_date), coalesce(p_end_date, current_date)) as start_date,
      greatest(coalesce(p_start_date, current_date), coalesce(p_end_date, current_date)) as end_date
  )
  select
    tpe.performed_on as event_date,
    count(*)::integer as pr_count,
    count(*) filter (where tpe.is_key_exercise)::integer as key_pr_count,
    count(distinct tpe.exercise_id)::integer as distinct_exercises
  from public.training_pr_events tpe
  join target_user tu on tu.user_id = tpe.user_id
  join bounds b on tpe.performed_on between b.start_date and b.end_date
  where public.training_can_manage_user(tu.user_id)
  group by tpe.performed_on
  order by tpe.performed_on asc;
$$;

drop function if exists public.training_get_workout_timeline_events(uuid,date,date);
create function public.training_get_workout_timeline_events(
  p_user_id uuid default auth.uid(),
  p_start_date date default current_date - 6,
  p_end_date date default current_date
)
returns table (
  event_date date,
  workout_id bigint,
  weekly_day_id bigint,
  weekly_day_index integer,
  weekly_day_name text,
  completed_sets integer,
  total_sets integer,
  completed_key_exercises integer,
  total_key_exercises integer,
  is_completed boolean,
  has_pr boolean,
  pr_count integer
)
language sql
security definer
stable
set search_path = public
as $$
  with bounds as (
    select
      least(coalesce(p_start_date, current_date), coalesce(p_end_date, current_date)) as start_date,
      greatest(coalesce(p_start_date, current_date), coalesce(p_end_date, current_date)) as end_date
  ), workouts_in_range as (
    select
      w.id as workout_id,
      w.performed_on as event_date,
      w.training_weekly_day_id as weekly_day_id,
      twd.day_index as weekly_day_index,
      twd.name as weekly_day_name
    from public.workouts w
    left join public.training_weekly_days twd on twd.id = w.training_weekly_day_id
    join bounds b
      on w.performed_on between b.start_date and b.end_date
    where w.user_id = p_user_id
  ), sets_by_workout as (
    select
      we.workout_id,
      count(es.id)::integer as total_sets,
      count(es.id) filter (
        where es.reps is not null
           or es.weight is not null
           or es.rir is not null
      )::integer as completed_sets
    from public.workout_exercises we
    left join public.exercise_sets es on es.workout_exercise_id = we.id
    group by we.workout_id
  ), key_by_workout as (
    select
      we.workout_id,
      count(*) filter (where coalesce(tbe.is_key_exercise, false))::integer as total_key_exercises,
      count(*) filter (
        where coalesce(tbe.is_key_exercise, false)
          and exists (
            select 1
            from public.exercise_sets es2
            where es2.workout_exercise_id = we.id
              and (
                es2.reps is not null
                or es2.weight is not null
                or es2.rir is not null
              )
          )
      )::integer as completed_key_exercises
    from public.workout_exercises we
    left join public.training_block_exercises tbe on tbe.id = we.training_block_exercise_id
    group by we.workout_id
  ), pr_by_workout as (
    select
      tpe.workout_id,
      count(*)::integer as pr_count
    from public.training_pr_events tpe
    join workouts_in_range wr on wr.workout_id = tpe.workout_id
    group by tpe.workout_id
  )
  select
    wr.event_date,
    wr.workout_id,
    wr.weekly_day_id,
    wr.weekly_day_index,
    wr.weekly_day_name,
    coalesce(sbw.completed_sets, 0) as completed_sets,
    coalesce(sbw.total_sets, 0) as total_sets,
    coalesce(kbw.completed_key_exercises, 0) as completed_key_exercises,
    coalesce(kbw.total_key_exercises, 0) as total_key_exercises,
    (
      coalesce(sbw.total_sets, 0) > 0
      and coalesce(sbw.completed_sets, 0) >= coalesce(sbw.total_sets, 0)
    ) as is_completed,
    (coalesce(pbw.pr_count, 0) > 0) as has_pr,
    coalesce(pbw.pr_count, 0) as pr_count
  from workouts_in_range wr
  left join sets_by_workout sbw on sbw.workout_id = wr.workout_id
  left join key_by_workout kbw on kbw.workout_id = wr.workout_id
  left join pr_by_workout pbw on pbw.workout_id = wr.workout_id
  where public.training_can_manage_user(p_user_id)
  order by wr.event_date asc, wr.workout_id asc;
$$;

grant all on table public.training_pr_events to anon, authenticated, service_role;
grant usage, select on sequence public.training_pr_events_id_seq to anon, authenticated, service_role;

grant execute on function public.training_refresh_workout_prs(bigint) to anon, authenticated, service_role;
grant execute on function public.training_refresh_workout_prs_by_workout_exercise(bigint) to anon, authenticated, service_role;
grant execute on function public.training_get_pr_events(uuid,date,date) to anon, authenticated, service_role;
grant execute on function public.training_get_workout_timeline_events(uuid,date,date) to anon, authenticated, service_role;
