-- Persist weekly volume targets by muscle for each weekly routine
-- and daily step counter for training progress visualization.

create table if not exists public.training_weekly_routine_muscle_targets (
  id bigint generated by default as identity primary key,
  weekly_routine_id bigint not null references public.training_weekly_routines(id) on delete cascade,
  muscle_id bigint not null references public.muscles(id),
  target_sets numeric(6,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (weekly_routine_id, muscle_id),
  check (target_sets >= 0 and target_sets <= 200)
);

create index if not exists training_weekly_routine_muscle_targets_routine_idx
  on public.training_weekly_routine_muscle_targets (weekly_routine_id);

create index if not exists training_weekly_routine_muscle_targets_muscle_idx
  on public.training_weekly_routine_muscle_targets (muscle_id);

create table if not exists public.training_daily_steps (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  step_date date not null,
  steps integer not null default 0,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, step_date),
  check (steps >= 0 and steps <= 200000),
  check (source in ('manual', 'wearable', 'sync'))
);

create index if not exists training_daily_steps_user_date_idx
  on public.training_daily_steps (user_id, step_date);

create or replace function public.set_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_training_weekly_routine_muscle_targets_updated_at
  on public.training_weekly_routine_muscle_targets;
create trigger trg_training_weekly_routine_muscle_targets_updated_at
before update on public.training_weekly_routine_muscle_targets
for each row
execute function public.set_updated_at_column();

drop trigger if exists trg_training_daily_steps_updated_at
  on public.training_daily_steps;
create trigger trg_training_daily_steps_updated_at
before update on public.training_daily_steps
for each row
execute function public.set_updated_at_column();

alter table public.training_weekly_routine_muscle_targets enable row level security;
alter table public.training_daily_steps enable row level security;

drop policy if exists "Allow admin full access on training_weekly_routine_muscle_targets" on public.training_weekly_routine_muscle_targets;
create policy "Allow admin full access on training_weekly_routine_muscle_targets"
on public.training_weekly_routine_muscle_targets
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_weekly_routine_muscle_targets" on public.training_weekly_routine_muscle_targets;
create policy "Allow users to manage own training_weekly_routine_muscle_targets"
on public.training_weekly_routine_muscle_targets
for all
using (
  exists (
    select 1
    from public.training_weekly_routines twr
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twr.id = training_weekly_routine_muscle_targets.weekly_routine_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.training_weekly_routines twr
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twr.id = training_weekly_routine_muscle_targets.weekly_routine_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_weekly_routine_muscle_targets" on public.training_weekly_routine_muscle_targets;
create policy "Coaches can view training_weekly_routine_muscle_targets"
on public.training_weekly_routine_muscle_targets
for select
using (
  exists (
    select 1
    from public.training_weekly_routines twr
    join public.mesocycles m on m.id = twr.mesocycle_id
    join public.coach_clients cc on cc.client_id = m.user_id
    where twr.id = training_weekly_routine_muscle_targets.weekly_routine_id
      and cc.coach_id = auth.uid()
  )
);

drop policy if exists "Allow admin full access on training_daily_steps" on public.training_daily_steps;
create policy "Allow admin full access on training_daily_steps"
on public.training_daily_steps
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_daily_steps" on public.training_daily_steps;
create policy "Allow users to manage own training_daily_steps"
on public.training_daily_steps
for all
using (training_daily_steps.user_id = auth.uid())
with check (training_daily_steps.user_id = auth.uid());

drop policy if exists "Coaches can view training_daily_steps" on public.training_daily_steps;
create policy "Coaches can view training_daily_steps"
on public.training_daily_steps
for select
using (
  exists (
    select 1
    from public.coach_clients cc
    where cc.client_id = training_daily_steps.user_id
      and cc.coach_id = auth.uid()
  )
);

grant all on table public.training_weekly_routine_muscle_targets to anon, authenticated, service_role;
grant all on table public.training_daily_steps to anon, authenticated, service_role;

create or replace function public.training_create_weekly_routine_quickstart_v2(
  p_weekly_routine_name text default null,
  p_cycle_days integer default null,
  p_days jsonb default '[]'::jsonb,
  p_objective_id bigint default null,
  p_start_date date default current_date,
  p_user_id uuid default auth.uid(),
  p_muscle_targets jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target_user_id uuid := coalesce(p_user_id, auth.uid());
  v_start_date date := coalesce(p_start_date, current_date);
  v_days_count integer;
  v_end_date date;
  v_objective_id bigint;
  v_objective_name text;
  v_mesocycle_id bigint;
  v_weekly_routine_id bigint;
  v_day jsonb;
  v_day_idx integer := 0;
  v_day_name text;
  v_weekly_day_id bigint;
  v_block jsonb;
  v_block_idx integer;
  v_block_type text;
  v_block_name text;
  v_weekly_day_block_id bigint;
  v_routine_name text := coalesce(nullif(trim(coalesce(p_weekly_routine_name, '')), ''), 'Rutina semanal');
begin
  if v_target_user_id is null then
    raise exception 'p_user_id is required';
  end if;

  if not public.training_can_manage_user(v_target_user_id) then
    raise exception 'not allowed to create training routine for user %', v_target_user_id;
  end if;

  if p_days is null or jsonb_typeof(p_days) <> 'array' or jsonb_array_length(p_days) = 0 then
    raise exception 'p_days must be a non-empty JSON array';
  end if;

  v_days_count := coalesce(p_cycle_days, jsonb_array_length(p_days));

  if v_days_count <> jsonb_array_length(p_days) then
    raise exception 'p_cycle_days (%) must match p_days length (%)', v_days_count, jsonb_array_length(p_days);
  end if;

  if v_days_count < 4 or v_days_count > 14 then
    raise exception 'p_cycle_days must be between 4 and 14';
  end if;

  if p_muscle_targets is not null and jsonb_typeof(p_muscle_targets) <> 'array' then
    raise exception 'p_muscle_targets must be a JSON array';
  end if;

  if p_objective_id is null then
    select o.id, o.name
    into v_objective_id, v_objective_name
    from public.training_objectives o
    where o.is_active
    order by o.display_order asc, o.id asc
    limit 1;
  else
    select o.id, o.name
    into v_objective_id, v_objective_name
    from public.training_objectives o
    where o.id = p_objective_id
      and o.is_active;
  end if;

  if v_objective_id is null then
    raise exception 'no active training objective found';
  end if;

  v_end_date := v_start_date + (v_days_count - 1);

  insert into public.mesocycles (
    user_id,
    name,
    objective,
    objective_id,
    start_date,
    end_date,
    sessions_per_week
  )
  values (
    v_target_user_id,
    v_routine_name || ' - ' || to_char(v_start_date, 'YYYY-MM-DD'),
    v_objective_name,
    v_objective_id,
    v_start_date,
    v_end_date,
    v_days_count
  )
  returning id into v_mesocycle_id;

  insert into public.training_weekly_routines (
    mesocycle_id,
    name,
    sessions_per_week,
    is_default
  )
  values (
    v_mesocycle_id,
    v_routine_name,
    v_days_count,
    true
  )
  returning id into v_weekly_routine_id;

  for v_day in
    select value from jsonb_array_elements(p_days)
  loop
    v_day_idx := v_day_idx + 1;
    v_day_name := nullif(trim(coalesce(v_day->>'name', '')), '');

    insert into public.training_weekly_days (
      weekly_routine_id,
      day_index,
      name
    )
    values (
      v_weekly_routine_id,
      v_day_idx,
      coalesce(v_day_name, 'Dia ' || v_day_idx::text)
    )
    returning id into v_weekly_day_id;

    if v_day ? 'blocks'
      and jsonb_typeof(v_day->'blocks') = 'array'
      and jsonb_array_length(v_day->'blocks') > 0 then
      v_block_idx := 0;

      for v_block in
        select value from jsonb_array_elements(v_day->'blocks')
      loop
        v_block_idx := v_block_idx + 1;
        v_block_type := lower(trim(coalesce(v_block->>'type', '')));

        if v_block_type = ''
          or v_block_type not in (
            'torso','pierna','fullbody','push','pull','core','cardio','movilidad','custom'
          ) then
          v_block_type := 'custom';
        end if;

        v_block_name := nullif(trim(coalesce(v_block->>'name', v_block->>'label', '')), '');

        insert into public.training_weekly_day_blocks (
          weekly_day_id,
          block_order,
          block_type,
          name
        )
        values (
          v_weekly_day_id,
          v_block_idx,
          v_block_type,
          v_block_name
        )
        returning id into v_weekly_day_block_id;

        if v_block ? 'exercises'
          and jsonb_typeof(v_block->'exercises') = 'array'
          and jsonb_array_length(v_block->'exercises') > 0 then
          insert into public.training_block_exercises (
            weekly_day_block_id,
            exercise_id,
            exercise_order,
            preferred_equipment_id,
            target_sets,
            target_reps_min,
            target_reps_max,
            progression_increment_kg,
            backoff_percentage,
            is_key_exercise,
            notes
          )
          select
            v_weekly_day_block_id,
            nullif(trim(coalesce(x.value->>'exercise_id', '')), '')::bigint,
            x.ordinality::integer,
            nullif(trim(coalesce(x.value->>'preferred_equipment_id', '')), '')::bigint,
            coalesce(nullif(trim(coalesce(x.value->>'target_sets', '')), '')::integer, 3),
            coalesce(nullif(trim(coalesce(x.value->>'target_reps_min', '')), '')::integer, 8),
            coalesce(nullif(trim(coalesce(x.value->>'target_reps_max', '')), '')::integer, 12),
            coalesce(nullif(trim(coalesce(x.value->>'progression_increment_kg', '')), '')::integer, 5),
            coalesce(nullif(trim(coalesce(x.value->>'backoff_percentage', '')), '')::numeric, 0.800),
            coalesce(nullif(trim(coalesce(x.value->>'is_key_exercise', '')), '')::boolean, x.ordinality = 1),
            nullif(trim(coalesce(x.value->>'notes', '')), '')
          from jsonb_array_elements(v_block->'exercises') with ordinality as x(value, ordinality)
          where nullif(trim(coalesce(x.value->>'exercise_id', '')), '') is not null;
        end if;
      end loop;
    else
      insert into public.training_weekly_day_blocks (
        weekly_day_id,
        block_order,
        block_type,
        name
      )
      values (
        v_weekly_day_id,
        1,
        'custom',
        null
      );
    end if;
  end loop;

  if p_muscle_targets is not null
    and jsonb_typeof(p_muscle_targets) = 'array'
    and jsonb_array_length(p_muscle_targets) > 0 then
    insert into public.training_weekly_routine_muscle_targets (
      weekly_routine_id,
      muscle_id,
      target_sets
    )
    select
      v_weekly_routine_id,
      nullif(trim(coalesce(x.value->>'muscle_id', '')), '')::bigint,
      coalesce(nullif(trim(coalesce(x.value->>'target_sets', '')), '')::numeric, 0)
    from jsonb_array_elements(p_muscle_targets) as x(value)
    where nullif(trim(coalesce(x.value->>'muscle_id', '')), '') is not null
      and coalesce(nullif(trim(coalesce(x.value->>'target_sets', '')), '')::numeric, 0) > 0
    on conflict (weekly_routine_id, muscle_id)
    do update set
      target_sets = excluded.target_sets,
      updated_at = now();
  end if;

  insert into public.training_microcycles (
    mesocycle_id,
    sequence_index,
    name,
    objective_id,
    start_date,
    end_date,
    deload_week
  )
  values (
    v_mesocycle_id,
    1,
    'Microciclo 1',
    v_objective_id,
    v_start_date,
    v_end_date,
    false
  );

  return v_mesocycle_id;
end;
$$;

grant execute on function public.training_create_weekly_routine_quickstart_v2(text,integer,jsonb,bigint,date,uuid,jsonb)
to anon, authenticated, service_role;
