-- Training Zone V2 core model
-- Target hierarchy:
--   Mesocycle (long-term) -> Microcycles -> Weekly Routine -> Days -> Blocks -> Exercises
-- Keep workout tracking tables and add optional links to new planning entities.

-- 1) Weekly routine template per mesocycle
create table if not exists public.training_weekly_routines (
  id bigint generated by default as identity primary key,
  mesocycle_id bigint not null references public.mesocycles(id) on delete cascade,
  name text not null,
  sessions_per_week integer not null,
  is_default boolean not null default true,
  created_at timestamptz not null default now(),
  unique (mesocycle_id, name),
  check (sessions_per_week between 1 and 7)
);

create index if not exists training_weekly_routines_mesocycle_idx
  on public.training_weekly_routines (mesocycle_id);

-- 2) Days inside weekly routine
create table if not exists public.training_weekly_days (
  id bigint generated by default as identity primary key,
  weekly_routine_id bigint not null references public.training_weekly_routines(id) on delete cascade,
  day_index integer not null,
  name text,
  created_at timestamptz not null default now(),
  unique (weekly_routine_id, day_index),
  check (day_index between 1 and 7)
);

create index if not exists training_weekly_days_routine_idx
  on public.training_weekly_days (weekly_routine_id, day_index);

-- 3) Blocks within each training day
create table if not exists public.training_weekly_day_blocks (
  id bigint generated by default as identity primary key,
  weekly_day_id bigint not null references public.training_weekly_days(id) on delete cascade,
  block_order integer not null,
  block_type text not null,
  name text,
  created_at timestamptz not null default now(),
  unique (weekly_day_id, block_order),
  check (block_order >= 1),
  check (
    block_type in (
      'torso','pierna','fullbody','push','pull','core','cardio','movilidad','custom'
    )
  )
);

create index if not exists training_weekly_day_blocks_day_idx
  on public.training_weekly_day_blocks (weekly_day_id, block_order);

-- 4) Base exercise prescription per block
create table if not exists public.training_block_exercises (
  id bigint generated by default as identity primary key,
  weekly_day_block_id bigint not null references public.training_weekly_day_blocks(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id),
  exercise_order integer not null,
  preferred_equipment_id bigint references public.equipment(id),
  target_sets integer not null default 3,
  target_reps_min integer not null default 8,
  target_reps_max integer not null default 12,
  progression_increment_kg integer not null default 5,
  backoff_percentage numeric(4,3) not null default 0.800,
  is_key_exercise boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  unique (weekly_day_block_id, exercise_order),
  check (target_sets between 1 and 20),
  check (target_reps_min between 1 and 60),
  check (target_reps_max between target_reps_min and 60),
  check (progression_increment_kg between 0 and 50),
  check (backoff_percentage > 0 and backoff_percentage <= 1)
);

create index if not exists training_block_exercises_block_idx
  on public.training_block_exercises (weekly_day_block_id, exercise_order);

create index if not exists training_block_exercises_exercise_idx
  on public.training_block_exercises (exercise_id);

-- 5) Microcycles: short-term progression blocks inside a mesocycle
create table if not exists public.training_microcycles (
  id bigint generated by default as identity primary key,
  mesocycle_id bigint not null references public.mesocycles(id) on delete cascade,
  sequence_index integer not null,
  name text not null,
  objective_id bigint references public.training_objectives(id),
  objective_notes text,
  start_date date not null,
  end_date date not null,
  deload_week boolean not null default false,
  created_at timestamptz not null default now(),
  unique (mesocycle_id, sequence_index),
  check (sequence_index >= 1),
  check (end_date >= start_date)
);

create index if not exists training_microcycles_mesocycle_idx
  on public.training_microcycles (mesocycle_id, sequence_index);

create index if not exists training_microcycles_date_idx
  on public.training_microcycles (start_date, end_date);

-- 6) Block focus per microcycle.
-- A block focus can target exactly one axis: movement pattern, muscle, joint, or exercise.
-- key_exercise_id captures the concrete exercise anchor used for progression.
create table if not exists public.training_microcycle_block_focuses (
  id bigint generated by default as identity primary key,
  microcycle_id bigint not null references public.training_microcycles(id) on delete cascade,
  weekly_day_block_id bigint not null references public.training_weekly_day_blocks(id) on delete cascade,
  focus_type text not null,
  movement_pattern_id bigint references public.training_movement_patterns(id),
  muscle_id bigint references public.muscles(id),
  joint_id bigint references public.joints(id),
  focus_exercise_id bigint references public.exercises(id),
  key_exercise_id bigint references public.exercises(id),
  notes text,
  created_at timestamptz not null default now(),
  unique (microcycle_id, weekly_day_block_id),
  check (focus_type in ('movement_pattern','muscle','joint','exercise')),
  check (
    (focus_type = 'movement_pattern' and movement_pattern_id is not null and muscle_id is null and joint_id is null and focus_exercise_id is null)
    or (focus_type = 'muscle' and movement_pattern_id is null and muscle_id is not null and joint_id is null and focus_exercise_id is null)
    or (focus_type = 'joint' and movement_pattern_id is null and muscle_id is null and joint_id is not null and focus_exercise_id is null)
    or (focus_type = 'exercise' and movement_pattern_id is null and muscle_id is null and joint_id is null and focus_exercise_id is not null)
  )
);

create index if not exists training_microcycle_focuses_microcycle_idx
  on public.training_microcycle_block_focuses (microcycle_id);

create index if not exists training_microcycle_focuses_block_idx
  on public.training_microcycle_block_focuses (weekly_day_block_id);

-- Ensure block and microcycle belong to the same mesocycle through weekly routine chain.
create or replace function public.validate_training_microcycle_block_focus()
returns trigger
language plpgsql
as $$
declare
  v_microcycle_mesocycle_id bigint;
  v_block_mesocycle_id bigint;
begin
  select tm.mesocycle_id
  into v_microcycle_mesocycle_id
  from public.training_microcycles tm
  where tm.id = new.microcycle_id;

  select twr.mesocycle_id
  into v_block_mesocycle_id
  from public.training_weekly_day_blocks twdb
  join public.training_weekly_days twd on twd.id = twdb.weekly_day_id
  join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
  where twdb.id = new.weekly_day_block_id;

  if v_microcycle_mesocycle_id is null then
    raise exception 'microcycle_id % not found', new.microcycle_id;
  end if;

  if v_block_mesocycle_id is null then
    raise exception 'weekly_day_block_id % not found', new.weekly_day_block_id;
  end if;

  if v_microcycle_mesocycle_id <> v_block_mesocycle_id then
    raise exception 'weekly_day_block_id % belongs to mesocycle %, but microcycle_id % belongs to mesocycle %',
      new.weekly_day_block_id, v_block_mesocycle_id, new.microcycle_id, v_microcycle_mesocycle_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validate_training_microcycle_block_focus on public.training_microcycle_block_focuses;
create trigger trg_validate_training_microcycle_block_focus
before insert or update of microcycle_id, weekly_day_block_id
on public.training_microcycle_block_focuses
for each row
execute function public.validate_training_microcycle_block_focus();

-- 7) Optional links from execution tables to the new planning model
alter table public.workouts
  add column if not exists training_microcycle_id bigint references public.training_microcycles(id) on delete set null,
  add column if not exists training_weekly_routine_id bigint references public.training_weekly_routines(id) on delete set null,
  add column if not exists training_weekly_day_id bigint references public.training_weekly_days(id) on delete set null;

create index if not exists workouts_training_microcycle_idx
  on public.workouts (training_microcycle_id);

create index if not exists workouts_training_weekly_day_idx
  on public.workouts (training_weekly_day_id);

alter table public.workout_exercises
  add column if not exists training_weekly_day_block_id bigint references public.training_weekly_day_blocks(id) on delete set null,
  add column if not exists training_block_exercise_id bigint references public.training_block_exercises(id) on delete set null;

create index if not exists workout_exercises_training_block_idx
  on public.workout_exercises (training_weekly_day_block_id);

create index if not exists workout_exercises_training_block_exercise_idx
  on public.workout_exercises (training_block_exercise_id);

-- 8) RLS
alter table public.training_weekly_routines enable row level security;
alter table public.training_weekly_days enable row level security;
alter table public.training_weekly_day_blocks enable row level security;
alter table public.training_block_exercises enable row level security;
alter table public.training_microcycles enable row level security;
alter table public.training_microcycle_block_focuses enable row level security;

-- training_weekly_routines policies
drop policy if exists "Allow admin full access on training_weekly_routines" on public.training_weekly_routines;
create policy "Allow admin full access on training_weekly_routines"
on public.training_weekly_routines
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_weekly_routines" on public.training_weekly_routines;
create policy "Allow users to manage own training_weekly_routines"
on public.training_weekly_routines
for all
using (
  exists (
    select 1
    from public.mesocycles m
    where m.id = training_weekly_routines.mesocycle_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.mesocycles m
    where m.id = training_weekly_routines.mesocycle_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_weekly_routines" on public.training_weekly_routines;
create policy "Coaches can view training_weekly_routines"
on public.training_weekly_routines
for select
using (
  exists (
    select 1
    from public.mesocycles m
    join public.coach_clients cc on cc.client_id = m.user_id
    where m.id = training_weekly_routines.mesocycle_id
      and cc.coach_id = auth.uid()
  )
);

-- training_weekly_days policies
drop policy if exists "Allow admin full access on training_weekly_days" on public.training_weekly_days;
create policy "Allow admin full access on training_weekly_days"
on public.training_weekly_days
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_weekly_days" on public.training_weekly_days;
create policy "Allow users to manage own training_weekly_days"
on public.training_weekly_days
for all
using (
  exists (
    select 1
    from public.training_weekly_routines twr
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twr.id = training_weekly_days.weekly_routine_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.training_weekly_routines twr
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twr.id = training_weekly_days.weekly_routine_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_weekly_days" on public.training_weekly_days;
create policy "Coaches can view training_weekly_days"
on public.training_weekly_days
for select
using (
  exists (
    select 1
    from public.training_weekly_routines twr
    join public.mesocycles m on m.id = twr.mesocycle_id
    join public.coach_clients cc on cc.client_id = m.user_id
    where twr.id = training_weekly_days.weekly_routine_id
      and cc.coach_id = auth.uid()
  )
);

-- training_weekly_day_blocks policies
drop policy if exists "Allow admin full access on training_weekly_day_blocks" on public.training_weekly_day_blocks;
create policy "Allow admin full access on training_weekly_day_blocks"
on public.training_weekly_day_blocks
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_weekly_day_blocks" on public.training_weekly_day_blocks;
create policy "Allow users to manage own training_weekly_day_blocks"
on public.training_weekly_day_blocks
for all
using (
  exists (
    select 1
    from public.training_weekly_days twd
    join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twd.id = training_weekly_day_blocks.weekly_day_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.training_weekly_days twd
    join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twd.id = training_weekly_day_blocks.weekly_day_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_weekly_day_blocks" on public.training_weekly_day_blocks;
create policy "Coaches can view training_weekly_day_blocks"
on public.training_weekly_day_blocks
for select
using (
  exists (
    select 1
    from public.training_weekly_days twd
    join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
    join public.mesocycles m on m.id = twr.mesocycle_id
    join public.coach_clients cc on cc.client_id = m.user_id
    where twd.id = training_weekly_day_blocks.weekly_day_id
      and cc.coach_id = auth.uid()
  )
);

-- training_block_exercises policies
drop policy if exists "Allow admin full access on training_block_exercises" on public.training_block_exercises;
create policy "Allow admin full access on training_block_exercises"
on public.training_block_exercises
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_block_exercises" on public.training_block_exercises;
create policy "Allow users to manage own training_block_exercises"
on public.training_block_exercises
for all
using (
  exists (
    select 1
    from public.training_weekly_day_blocks twdb
    join public.training_weekly_days twd on twd.id = twdb.weekly_day_id
    join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twdb.id = training_block_exercises.weekly_day_block_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.training_weekly_day_blocks twdb
    join public.training_weekly_days twd on twd.id = twdb.weekly_day_id
    join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
    join public.mesocycles m on m.id = twr.mesocycle_id
    where twdb.id = training_block_exercises.weekly_day_block_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_block_exercises" on public.training_block_exercises;
create policy "Coaches can view training_block_exercises"
on public.training_block_exercises
for select
using (
  exists (
    select 1
    from public.training_weekly_day_blocks twdb
    join public.training_weekly_days twd on twd.id = twdb.weekly_day_id
    join public.training_weekly_routines twr on twr.id = twd.weekly_routine_id
    join public.mesocycles m on m.id = twr.mesocycle_id
    join public.coach_clients cc on cc.client_id = m.user_id
    where twdb.id = training_block_exercises.weekly_day_block_id
      and cc.coach_id = auth.uid()
  )
);

-- training_microcycles policies
drop policy if exists "Allow admin full access on training_microcycles" on public.training_microcycles;
create policy "Allow admin full access on training_microcycles"
on public.training_microcycles
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_microcycles" on public.training_microcycles;
create policy "Allow users to manage own training_microcycles"
on public.training_microcycles
for all
using (
  exists (
    select 1
    from public.mesocycles m
    where m.id = training_microcycles.mesocycle_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.mesocycles m
    where m.id = training_microcycles.mesocycle_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_microcycles" on public.training_microcycles;
create policy "Coaches can view training_microcycles"
on public.training_microcycles
for select
using (
  exists (
    select 1
    from public.mesocycles m
    join public.coach_clients cc on cc.client_id = m.user_id
    where m.id = training_microcycles.mesocycle_id
      and cc.coach_id = auth.uid()
  )
);

-- training_microcycle_block_focuses policies
drop policy if exists "Allow admin full access on training_microcycle_block_focuses" on public.training_microcycle_block_focuses;
create policy "Allow admin full access on training_microcycle_block_focuses"
on public.training_microcycle_block_focuses
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to manage own training_microcycle_block_focuses" on public.training_microcycle_block_focuses;
create policy "Allow users to manage own training_microcycle_block_focuses"
on public.training_microcycle_block_focuses
for all
using (
  exists (
    select 1
    from public.training_microcycles tm
    join public.mesocycles m on m.id = tm.mesocycle_id
    where tm.id = training_microcycle_block_focuses.microcycle_id
      and m.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.training_microcycles tm
    join public.mesocycles m on m.id = tm.mesocycle_id
    where tm.id = training_microcycle_block_focuses.microcycle_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Coaches can view training_microcycle_block_focuses" on public.training_microcycle_block_focuses;
create policy "Coaches can view training_microcycle_block_focuses"
on public.training_microcycle_block_focuses
for select
using (
  exists (
    select 1
    from public.training_microcycles tm
    join public.mesocycles m on m.id = tm.mesocycle_id
    join public.coach_clients cc on cc.client_id = m.user_id
    where tm.id = training_microcycle_block_focuses.microcycle_id
      and cc.coach_id = auth.uid()
  )
);

-- 9) Grants
grant all on table public.training_weekly_routines to anon, authenticated, service_role;
grant all on table public.training_weekly_days to anon, authenticated, service_role;
grant all on table public.training_weekly_day_blocks to anon, authenticated, service_role;
grant all on table public.training_block_exercises to anon, authenticated, service_role;
grant all on table public.training_microcycles to anon, authenticated, service_role;
grant all on table public.training_microcycle_block_focuses to anon, authenticated, service_role;

grant all on sequence public.training_weekly_routines_id_seq to anon, authenticated, service_role;
grant all on sequence public.training_weekly_days_id_seq to anon, authenticated, service_role;
grant all on sequence public.training_weekly_day_blocks_id_seq to anon, authenticated, service_role;
grant all on sequence public.training_block_exercises_id_seq to anon, authenticated, service_role;
grant all on sequence public.training_microcycles_id_seq to anon, authenticated, service_role;
grant all on sequence public.training_microcycle_block_focuses_id_seq to anon, authenticated, service_role;

-- 10) Cleanup legacy test planning data requested by product owner.
-- Keep workout history, but clear legacy mesocycle/routine planning data.
delete from public.routine_exercises;
delete from public.routine_day_blocks;
delete from public.routines;
delete from public.mesocycles;
