-- Beta foundation: mesocycles, routine days, exercise prescriptions and progression-aware workout generation

-- 1) Mesocycle/routine metadata
alter table public.mesocycles
  add column if not exists name text,
  add column if not exists sessions_per_week integer;

alter table public.routines
  add column if not exists day_index integer,
  add column if not exists day_type text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'mesocycles_sessions_per_week_check'
      and conrelid = 'public.mesocycles'::regclass
  ) then
    alter table public.mesocycles
      add constraint mesocycles_sessions_per_week_check
      check (sessions_per_week is null or sessions_per_week between 1 and 7);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routines_day_index_check'
      and conrelid = 'public.routines'::regclass
  ) then
    alter table public.routines
      add constraint routines_day_index_check
      check (day_index is null or day_index >= 1);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routines_day_type_check'
      and conrelid = 'public.routines'::regclass
  ) then
    alter table public.routines
      add constraint routines_day_type_check
      check (
        day_type is null
        or day_type in (
          'torso','pierna','fullbody','push','pull','upper','lower','core','cardio','movilidad','custom'
        )
      );
  end if;
end
$$;

create index if not exists routines_mesocycle_day_idx
  on public.routines (mesocycle_id, day_index);

-- 2) Exercise prescription per routine day
create table if not exists public.routine_exercises (
  id bigint generated by default as identity primary key,
  routine_id bigint not null references public.routines(id) on delete cascade,
  exercise_id bigint not null references public.exercises(id),
  exercise_order integer not null,
  preferred_equipment_id bigint references public.equipment(id),
  target_sets integer not null default 3,
  target_reps_min integer not null default 8,
  target_reps_max integer not null default 12,
  progression_increment_kg integer not null default 5,
  backoff_percentage numeric(4,3) not null default 0.800,
  notes text,
  created_at timestamptz not null default now(),
  unique (routine_id, exercise_order)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_exercises_target_sets_check'
      and conrelid = 'public.routine_exercises'::regclass
  ) then
    alter table public.routine_exercises
      add constraint routine_exercises_target_sets_check
      check (target_sets between 1 and 12);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_exercises_target_reps_min_check'
      and conrelid = 'public.routine_exercises'::regclass
  ) then
    alter table public.routine_exercises
      add constraint routine_exercises_target_reps_min_check
      check (target_reps_min between 1 and 60);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_exercises_target_reps_max_check'
      and conrelid = 'public.routine_exercises'::regclass
  ) then
    alter table public.routine_exercises
      add constraint routine_exercises_target_reps_max_check
      check (target_reps_max between target_reps_min and 60);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_exercises_progression_increment_kg_check'
      and conrelid = 'public.routine_exercises'::regclass
  ) then
    alter table public.routine_exercises
      add constraint routine_exercises_progression_increment_kg_check
      check (progression_increment_kg between 0 and 50);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'routine_exercises_backoff_percentage_check'
      and conrelid = 'public.routine_exercises'::regclass
  ) then
    alter table public.routine_exercises
      add constraint routine_exercises_backoff_percentage_check
      check (backoff_percentage > 0 and backoff_percentage <= 1);
  end if;
end
$$;

create index if not exists routine_exercises_routine_idx
  on public.routine_exercises (routine_id, exercise_order);

create index if not exists routine_exercises_exercise_idx
  on public.routine_exercises (exercise_id);

-- 3) Persist workout prescription snapshot
alter table public.workout_exercises
  add column if not exists routine_exercise_id bigint references public.routine_exercises(id) on delete set null,
  add column if not exists prescribed_sets integer,
  add column if not exists prescribed_reps_min integer,
  add column if not exists prescribed_reps_max integer,
  add column if not exists prescribed_increment_kg integer,
  add column if not exists prescribed_backoff_percentage numeric(4,3);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'workout_exercises_prescribed_sets_check'
      and conrelid = 'public.workout_exercises'::regclass
  ) then
    alter table public.workout_exercises
      add constraint workout_exercises_prescribed_sets_check
      check (prescribed_sets is null or prescribed_sets between 1 and 12);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'workout_exercises_prescribed_reps_min_check'
      and conrelid = 'public.workout_exercises'::regclass
  ) then
    alter table public.workout_exercises
      add constraint workout_exercises_prescribed_reps_min_check
      check (prescribed_reps_min is null or prescribed_reps_min between 1 and 60);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'workout_exercises_prescribed_reps_max_check'
      and conrelid = 'public.workout_exercises'::regclass
  ) then
    alter table public.workout_exercises
      add constraint workout_exercises_prescribed_reps_max_check
      check (
        prescribed_reps_max is null
        or prescribed_reps_min is null
        or prescribed_reps_max >= prescribed_reps_min
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'workout_exercises_prescribed_increment_kg_check'
      and conrelid = 'public.workout_exercises'::regclass
  ) then
    alter table public.workout_exercises
      add constraint workout_exercises_prescribed_increment_kg_check
      check (prescribed_increment_kg is null or prescribed_increment_kg between 0 and 50);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'workout_exercises_prescribed_backoff_percentage_check'
      and conrelid = 'public.workout_exercises'::regclass
  ) then
    alter table public.workout_exercises
      add constraint workout_exercises_prescribed_backoff_percentage_check
      check (prescribed_backoff_percentage is null or (prescribed_backoff_percentage > 0 and prescribed_backoff_percentage <= 1));
  end if;
end
$$;

-- 4) Extend exercise sets with set targets + uniqueness
alter table public.exercise_sets
  add column if not exists target_reps_min integer,
  add column if not exists target_reps_max integer,
  add column if not exists target_weight integer,
  add column if not exists is_warmup boolean not null default false;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'exercise_sets_target_reps_min_check'
      and conrelid = 'public.exercise_sets'::regclass
  ) then
    alter table public.exercise_sets
      add constraint exercise_sets_target_reps_min_check
      check (target_reps_min is null or target_reps_min between 1 and 60);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'exercise_sets_target_reps_max_check'
      and conrelid = 'public.exercise_sets'::regclass
  ) then
    alter table public.exercise_sets
      add constraint exercise_sets_target_reps_max_check
      check (
        target_reps_max is null
        or target_reps_min is null
        or target_reps_max >= target_reps_min
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'exercise_sets_target_weight_check'
      and conrelid = 'public.exercise_sets'::regclass
  ) then
    alter table public.exercise_sets
      add constraint exercise_sets_target_weight_check
      check (target_weight is null or target_weight >= 0);
  end if;
end
$$;

create unique index if not exists exercise_sets_workout_exercise_setno_unique
  on public.exercise_sets (workout_exercise_id, set_no)
  where set_no is not null;

-- 5) RLS for routine_exercises
alter table public.routine_exercises enable row level security;

drop policy if exists "Allow admin full access on routine_exercises" on public.routine_exercises;
create policy "Allow admin full access on routine_exercises"
on public.routine_exercises
for all
using (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'admin'
  )
);

drop policy if exists "Allow users to access their own routine_exercises" on public.routine_exercises;
create policy "Allow users to access their own routine_exercises"
on public.routine_exercises
for all
using (
  exists (
    select 1
    from public.routines r
    where r.id = routine_exercises.routine_id
      and r.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.routines r
    where r.id = routine_exercises.routine_id
      and r.user_id = auth.uid()
  )
);

-- Optional coach read of client routine prescriptions
drop policy if exists "Coaches can view routine_exercises for clients" on public.routine_exercises;
create policy "Coaches can view routine_exercises for clients"
on public.routine_exercises
for select
using (
  exists (
    select 1
    from public.routines r
    join public.coach_clients cc on cc.client_id = r.user_id
    where r.id = routine_exercises.routine_id
      and cc.coach_id = auth.uid()
  )
);

grant all on table public.routine_exercises to anon, authenticated, service_role;
grant all on sequence public.routine_exercises_id_seq to anon, authenticated, service_role;

-- 6) Helper: latest progression decision for exercise+equipment
create or replace function public.suggest_next_top_set_weight(
  p_user_id uuid,
  p_exercise_id bigint,
  p_equipment_id bigint,
  p_target_reps_max integer,
  p_increment_kg integer default 5
)
returns integer
language plpgsql
stable
as $$
declare
  v_last_weight integer;
  v_min_reps integer;
  v_result integer;
begin
  select stats.top_weight, stats.min_reps
  into v_last_weight, v_min_reps
  from (
    select we.id,
           max(es.weight) filter (where es.set_no = 1 and es.weight is not null) as top_weight,
           min(es.reps) filter (where not coalesce(es.is_warmup, false) and es.reps is not null) as min_reps,
           max(w.performed_on) as performed_on
    from public.workout_exercises we
    join public.workouts w on w.id = we.workout_id
    left join public.exercise_sets es on es.workout_exercise_id = we.id
    where w.user_id = p_user_id
      and we.exercise_id = p_exercise_id
      and coalesce(we.performed_equipment_id, -1) = coalesce(p_equipment_id, -1)
    group by we.id
    order by performed_on desc, we.id desc
    limit 1
  ) stats;

  if v_last_weight is null then
    return null;
  end if;

  if v_min_reps is not null and v_min_reps >= greatest(p_target_reps_max - 1, 1) then
    v_result := v_last_weight + greatest(coalesce(p_increment_kg, 0), 0);
  else
    v_result := v_last_weight;
  end if;

  return greatest(v_result, 0);
end;
$$;

-- 7) Create workout from routine with target sets and progression-aware load suggestions
create or replace function public.create_workout_from_routine(
  p_routine_id bigint,
  p_performed_on date default current_date
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_workout_id bigint;
  v_is_admin boolean;
  v_is_coach boolean;
  rec record;
  v_equipment_id bigint;
  v_top_weight integer;
  v_backoff_weight integer;
begin
  select r.user_id into v_user_id
  from public.routines r
  where r.id = p_routine_id;

  if v_user_id is null then
    raise exception 'routine_id % not found', p_routine_id;
  end if;

  select exists (
    select 1
    from public.user_roles ur
    join public.roles rl on rl.id = ur.role_id
    where ur.user_id = auth.uid()
      and rl.role = 'admin'
  ) into v_is_admin;

  select exists (
    select 1
    from public.coach_clients cc
    where cc.coach_id = auth.uid()
      and cc.client_id = v_user_id
  ) into v_is_coach;

  if auth.uid() is distinct from v_user_id and not v_is_admin and not v_is_coach then
    raise exception 'not allowed to create workout for this routine';
  end if;

  insert into public.workouts (user_id, routine_id, performed_on)
  values (v_user_id, p_routine_id, coalesce(p_performed_on, current_date))
  returning id into v_workout_id;

  for rec in
    select re.id as routine_exercise_id,
           re.exercise_id,
           re.exercise_order,
           re.preferred_equipment_id,
           re.target_sets,
           re.target_reps_min,
           re.target_reps_max,
           re.progression_increment_kg,
           re.backoff_percentage,
           e.equipment_id as default_equipment_id,
           e.default_weight
    from public.routine_exercises re
    join public.exercises e on e.id = re.exercise_id
    where re.routine_id = p_routine_id
    order by re.exercise_order
  loop
    v_equipment_id := coalesce(rec.preferred_equipment_id, rec.default_equipment_id);

    v_top_weight := public.suggest_next_top_set_weight(
      v_user_id,
      rec.exercise_id,
      v_equipment_id,
      rec.target_reps_max,
      rec.progression_increment_kg
    );

    if v_top_weight is null then
      v_top_weight := coalesce(rec.default_weight, 0);
    end if;

    v_top_weight := greatest(v_top_weight, 0);
    v_backoff_weight := greatest(round(v_top_weight * rec.backoff_percentage)::integer, 0);

    insert into public.workout_exercises (
      workout_id,
      exercise_id,
      sequence,
      performed_equipment_id,
      routine_exercise_id,
      prescribed_sets,
      prescribed_reps_min,
      prescribed_reps_max,
      prescribed_increment_kg,
      prescribed_backoff_percentage
    )
    values (
      v_workout_id,
      rec.exercise_id,
      rec.exercise_order,
      v_equipment_id,
      rec.routine_exercise_id,
      rec.target_sets,
      rec.target_reps_min,
      rec.target_reps_max,
      rec.progression_increment_kg,
      rec.backoff_percentage
    );

    -- seed target plan rows (set 1 top-set, remaining sets backoff)
    insert into public.exercise_sets (
      workout_exercise_id,
      set_no,
      target_reps_min,
      target_reps_max,
      target_weight,
      is_warmup
    )
    select we.id,
           gs,
           rec.target_reps_min,
           rec.target_reps_max,
           case when gs = 1 then v_top_weight else v_backoff_weight end,
           false
    from generate_series(1, rec.target_sets) gs
    join public.workout_exercises we
      on we.workout_id = v_workout_id
     and we.routine_exercise_id = rec.routine_exercise_id
    on conflict (workout_exercise_id, set_no) where set_no is not null do update
    set target_reps_min = excluded.target_reps_min,
        target_reps_max = excluded.target_reps_max,
        target_weight = excluded.target_weight,
        is_warmup = excluded.is_warmup;
  end loop;

  return v_workout_id;
end;
$$;

grant execute on function public.suggest_next_top_set_weight(uuid,bigint,bigint,integer,integer) to anon, authenticated, service_role;
grant execute on function public.create_workout_from_routine(bigint,date) to anon, authenticated, service_role;

-- 8) Helper: create a mesocycle split quickly (torso/pierna/fullbody etc.)
create or replace function public.create_mesocycle_with_split(
  p_name text,
  p_objective text,
  p_start_date date,
  p_end_date date,
  p_day_types text[]
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mesocycle_id bigint;
  v_day text;
  v_idx integer := 0;
begin
  if auth.uid() is null then
    raise exception 'auth required';
  end if;

  if p_day_types is null or array_length(p_day_types, 1) is null then
    raise exception 'p_day_types cannot be empty';
  end if;

  insert into public.mesocycles (user_id, name, objective, start_date, end_date, sessions_per_week)
  values (
    auth.uid(),
    p_name,
    p_objective,
    p_start_date,
    p_end_date,
    array_length(p_day_types, 1)
  )
  returning id into v_mesocycle_id;

  foreach v_day in array p_day_types
  loop
    v_idx := v_idx + 1;
    insert into public.routines (
      user_id,
      mesocycle_id,
      day_index,
      day_type,
      name
    )
    values (
      auth.uid(),
      v_mesocycle_id,
      v_idx,
      v_day,
      initcap(v_day) || ' D' || v_idx::text
    );
  end loop;

  return v_mesocycle_id;
end;
$$;

grant execute on function public.create_mesocycle_with_split(text,text,date,date,text[]) to anon, authenticated, service_role;
