-- =============================================================================
-- Fase 2: Unificar free_recipes + private_recipes → user_recipes
-- =============================================================================
-- Ejecutar con:
--   psql "postgresql://postgres:postgres@localhost:54322/postgres" \
--        -f supabase/migrations/20260304190000_create_user_recipes.sql
-- =============================================================================

BEGIN;

-- =============================================================================
-- SECTION 1: Crear tabla user_recipes (sin self-ref FKs aún)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.user_recipes (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               uuid NOT NULL,
    type                  text NOT NULL DEFAULT 'free' CHECK (type IN ('free', 'private')),
    name                  text,
    instructions          text,
    day_meal_id           bigint,
    diet_plan_id          bigint,
    prep_time_min         integer,
    difficulty            text,
    status                text CHECK (status IN (
                              'pending', 'approved_private', 'approved_general',
                              'kept_as_free_recipe', 'rejected')),
    -- Versioning / linaje (FK se añaden después de migrar datos)
    parent_user_recipe_id bigint,
    parent_recipe_id      bigint,
    source_user_recipe_id bigint,
    created_at            timestamp with time zone DEFAULT now(),
    -- Columnas temporales de tracking (se eliminan al final)
    _src_table            text,
    _src_id               bigint
);

ALTER TABLE public.user_recipes OWNER TO postgres;

-- =============================================================================
-- SECTION 2: Migrar datos desde free_recipes y private_recipes
-- =============================================================================

-- Free recipes → type='free', conservar status
INSERT INTO public.user_recipes (
    user_id, type, name, instructions, day_meal_id, diet_plan_id,
    prep_time_min, difficulty, status, parent_recipe_id, created_at,
    _src_table, _src_id
)
SELECT
    user_id, 'free', name, instructions, day_meal_id, diet_plan_id,
    prep_time_min, difficulty, status, parent_recipe_id, created_at,
    'free_recipes', id
FROM public.free_recipes;

-- Private recipes → type='private', status = NULL
INSERT INTO public.user_recipes (
    user_id, type, name, instructions, day_meal_id, diet_plan_id,
    prep_time_min, difficulty, created_at,
    _src_table, _src_id
)
SELECT
    user_id, 'private', name, instructions, day_meal_id, diet_plan_id,
    prep_time_min, difficulty, created_at,
    'private_recipes', id
FROM public.private_recipes;

-- Tabla de mapeo temporal (old_id → new_id por tipo)
CREATE TEMP TABLE ur_map AS
SELECT id AS new_id, _src_table, _src_id FROM public.user_recipes;

-- Verificación previa
DO $$
DECLARE
    free_count    integer;
    private_count integer;
    ur_count      integer;
BEGIN
    SELECT COUNT(*) INTO free_count FROM public.free_recipes;
    SELECT COUNT(*) INTO private_count FROM public.private_recipes;
    SELECT COUNT(*) INTO ur_count FROM public.user_recipes;

    IF ur_count <> free_count + private_count THEN
        RAISE EXCEPTION 'Migración incompleta: free_recipes=%, private_recipes=%, user_recipes=%',
            free_count, private_count, ur_count;
    END IF;
    RAISE NOTICE 'Migración OK: free=%, private=%, total=%', free_count, private_count, ur_count;
END $$;

-- =============================================================================
-- SECTION 3: Fijar referencias cruzadas dentro de user_recipes
-- =============================================================================

-- parent_user_recipe_id para free (era parent_free_recipe_id)
UPDATE public.user_recipes ur
SET parent_user_recipe_id = m_parent.new_id
FROM public.free_recipes fr
JOIN ur_map m_self   ON m_self._src_table = 'free_recipes'   AND m_self._src_id   = fr.id
JOIN ur_map m_parent ON m_parent._src_table = 'free_recipes' AND m_parent._src_id = fr.parent_free_recipe_id
WHERE fr.parent_free_recipe_id IS NOT NULL
  AND ur.id = m_self.new_id;

-- parent_user_recipe_id para private (era parent_private_recipe_id)
UPDATE public.user_recipes ur
SET parent_user_recipe_id = m_parent.new_id
FROM public.private_recipes pr
JOIN ur_map m_self   ON m_self._src_table = 'private_recipes'   AND m_self._src_id   = pr.id
JOIN ur_map m_parent ON m_parent._src_table = 'private_recipes' AND m_parent._src_id = pr.parent_private_recipe_id
WHERE pr.parent_private_recipe_id IS NOT NULL
  AND ur.id = m_self.new_id;

-- source_user_recipe_id para private (era source_free_recipe_id → apuntaba a free_recipes)
UPDATE public.user_recipes ur
SET source_user_recipe_id = m_free.new_id
FROM public.private_recipes pr
JOIN ur_map m_self ON m_self._src_table = 'private_recipes' AND m_self._src_id = pr.id
JOIN ur_map m_free ON m_free._src_table = 'free_recipes'    AND m_free._src_id = pr.source_free_recipe_id
WHERE pr.source_free_recipe_id IS NOT NULL
  AND ur.id = m_self.new_id;

-- =============================================================================
-- SECTION 4: Añadir FKs y constraints a user_recipes
-- =============================================================================

ALTER TABLE public.user_recipes
    ADD CONSTRAINT ur_user_fk          FOREIGN KEY (user_id)               REFERENCES public.profiles(user_id)    ON DELETE CASCADE,
    ADD CONSTRAINT ur_day_meal_fk      FOREIGN KEY (day_meal_id)           REFERENCES public.day_meals(id)        ON DELETE SET NULL,
    ADD CONSTRAINT ur_diet_plan_fk     FOREIGN KEY (diet_plan_id)          REFERENCES public.diet_plans(id)       ON DELETE SET NULL,
    ADD CONSTRAINT ur_parent_fk        FOREIGN KEY (parent_user_recipe_id) REFERENCES public.user_recipes(id)     ON DELETE SET NULL,
    ADD CONSTRAINT ur_source_fk        FOREIGN KEY (source_user_recipe_id) REFERENCES public.user_recipes(id)     ON DELETE SET NULL,
    ADD CONSTRAINT ur_parent_recipe_fk FOREIGN KEY (parent_recipe_id)      REFERENCES public.recipes(id)          ON DELETE SET NULL;

CREATE INDEX idx_user_recipes_user_id ON public.user_recipes(user_id);
CREATE INDEX idx_user_recipes_type    ON public.user_recipes(type);
CREATE INDEX idx_user_recipes_status  ON public.user_recipes(status) WHERE status IS NOT NULL;

-- =============================================================================
-- SECTION 5: Actualizar 7 tablas dependientes
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 5a. recipe_ingredients: free_recipe_id + private_recipe_id → user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.recipe_ingredients ADD COLUMN user_recipe_id bigint;

UPDATE public.recipe_ingredients ri
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'free_recipes' AND ri.free_recipe_id = m._src_id;

UPDATE public.recipe_ingredients ri
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND ri.private_recipe_id = m._src_id;

ALTER TABLE public.recipe_ingredients
    ADD CONSTRAINT ri_user_recipe_fk FOREIGN KEY (user_recipe_id)
    REFERENCES public.user_recipes(id) ON DELETE CASCADE;

-- DROP vistas y políticas que dependen de free_recipe_id / private_recipe_id
-- (deben eliminarse ANTES del DROP COLUMN; Section 9 los recrea)
DROP VIEW IF EXISTS public.free_recipe_ingredients;
DROP VIEW IF EXISTS public.private_recipe_ingredients;

DO $$
DECLARE
    pol_name text;
BEGIN
    FOR pol_name IN
        SELECT policyname FROM pg_policies
        WHERE tablename = 'recipe_ingredients'
          AND (qual ILIKE '%free_recipe_id%' OR qual ILIKE '%private_recipe_id%'
            OR with_check ILIKE '%free_recipe_id%' OR with_check ILIKE '%private_recipe_id%')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.recipe_ingredients', pol_name);
        RAISE NOTICE 'Dropped RLS policy: %', pol_name;
    END LOOP;
END $$;

ALTER TABLE public.recipe_ingredients
    DROP COLUMN free_recipe_id,
    DROP COLUMN private_recipe_id;

-- Actualizar CHECK constraint (ahora 3 FKs: recipe_id, diet_plan_recipe_id, user_recipe_id)
ALTER TABLE public.recipe_ingredients DROP CONSTRAINT IF EXISTS exactly_one_parent;
ALTER TABLE public.recipe_ingredients ADD CONSTRAINT exactly_one_parent CHECK (
    (recipe_id IS NOT NULL)::int +
    (diet_plan_recipe_id IS NOT NULL)::int +
    (user_recipe_id IS NOT NULL)::int = 1
);

DROP INDEX IF EXISTS idx_recipe_ingredients_free_recipe_id;
DROP INDEX IF EXISTS idx_recipe_ingredients_private_recipe_id;
DROP INDEX IF EXISTS idx_ri_free_recipe_id;
DROP INDEX IF EXISTS idx_ri_private_recipe_id;
CREATE INDEX idx_ri_user_recipe_id ON public.recipe_ingredients(user_recipe_id) WHERE user_recipe_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5b. free_recipe_occurrences: free_recipe_id → user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.free_recipe_occurrences ADD COLUMN user_recipe_id bigint;

UPDATE public.free_recipe_occurrences fro
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'free_recipes' AND fro.free_recipe_id = m._src_id;

ALTER TABLE public.free_recipe_occurrences
    ADD CONSTRAINT fro_user_recipe_fk FOREIGN KEY (user_recipe_id)
    REFERENCES public.user_recipes(id) ON DELETE CASCADE;

ALTER TABLE public.free_recipe_occurrences DROP COLUMN free_recipe_id;

-- ---------------------------------------------------------------------------
-- 5c. daily_meal_logs: private_recipe_id → user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.daily_meal_logs ADD COLUMN user_recipe_id bigint;

UPDATE public.daily_meal_logs dml
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND dml.private_recipe_id = m._src_id;

ALTER TABLE public.daily_meal_logs
    ADD CONSTRAINT dml_user_recipe_fk FOREIGN KEY (user_recipe_id)
    REFERENCES public.user_recipes(id) ON DELETE SET NULL;

ALTER TABLE public.daily_meal_logs DROP COLUMN private_recipe_id;

-- ---------------------------------------------------------------------------
-- 5d. daily_ingredient_adjustments: private_recipe_id → user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.daily_ingredient_adjustments ADD COLUMN user_recipe_id bigint;

UPDATE public.daily_ingredient_adjustments dia
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND dia.private_recipe_id = m._src_id;

ALTER TABLE public.daily_ingredient_adjustments
    ADD CONSTRAINT dia_user_recipe_fk FOREIGN KEY (user_recipe_id)
    REFERENCES public.user_recipes(id);

ALTER TABLE public.daily_ingredient_adjustments DROP COLUMN private_recipe_id;

-- ---------------------------------------------------------------------------
-- 5e. diet_change_requests: private_recipe_id → user_recipe_id
--                            requested_changes_private_recipe_id → requested_changes_user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.diet_change_requests
    ADD COLUMN user_recipe_id                    bigint,
    ADD COLUMN requested_changes_user_recipe_id  bigint;

UPDATE public.diet_change_requests dcr
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND dcr.private_recipe_id = m._src_id;

UPDATE public.diet_change_requests dcr
SET requested_changes_user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND dcr.requested_changes_private_recipe_id = m._src_id;

ALTER TABLE public.diet_change_requests
    ADD CONSTRAINT dcr_user_recipe_fk
        FOREIGN KEY (user_recipe_id) REFERENCES public.user_recipes(id) ON DELETE CASCADE,
    ADD CONSTRAINT dcr_req_changes_user_recipe_fk
        FOREIGN KEY (requested_changes_user_recipe_id) REFERENCES public.user_recipes(id) ON DELETE SET NULL;

ALTER TABLE public.diet_change_requests
    DROP COLUMN private_recipe_id,
    DROP COLUMN requested_changes_private_recipe_id;

-- Actualizar CHECK (diet_plan_recipe_id XOR user_recipe_id)
ALTER TABLE public.diet_change_requests DROP CONSTRAINT IF EXISTS check_one_recipe_id;
ALTER TABLE public.diet_change_requests ADD CONSTRAINT check_one_recipe_id CHECK (
    (diet_plan_recipe_id IS NOT NULL AND user_recipe_id IS NULL) OR
    (diet_plan_recipe_id IS NULL     AND user_recipe_id IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- 5f. equivalence_adjustments: source_free_recipe_id + source_private_recipe_id → source_user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.equivalence_adjustments ADD COLUMN source_user_recipe_id bigint;

UPDATE public.equivalence_adjustments ea
SET source_user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'free_recipes' AND ea.source_free_recipe_id = m._src_id;

UPDATE public.equivalence_adjustments ea
SET source_user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND ea.source_private_recipe_id = m._src_id;

ALTER TABLE public.equivalence_adjustments
    ADD CONSTRAINT ea_source_user_recipe_fk FOREIGN KEY (source_user_recipe_id)
    REFERENCES public.user_recipes(id) ON DELETE SET NULL;

ALTER TABLE public.equivalence_adjustments
    DROP COLUMN source_free_recipe_id,
    DROP COLUMN source_private_recipe_id;

-- ---------------------------------------------------------------------------
-- 5g. planned_meals: free_recipe_id + private_recipe_id → user_recipe_id
-- ---------------------------------------------------------------------------
ALTER TABLE public.planned_meals ADD COLUMN user_recipe_id bigint;

UPDATE public.planned_meals pm
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'free_recipes' AND pm.free_recipe_id = m._src_id;

UPDATE public.planned_meals pm
SET user_recipe_id = m.new_id
FROM ur_map m
WHERE m._src_table = 'private_recipes' AND pm.private_recipe_id = m._src_id;

ALTER TABLE public.planned_meals
    ADD CONSTRAINT pm_user_recipe_fk FOREIGN KEY (user_recipe_id)
    REFERENCES public.user_recipes(id) ON DELETE CASCADE;

ALTER TABLE public.planned_meals
    DROP COLUMN free_recipe_id,
    DROP COLUMN private_recipe_id;

-- Actualizar CHECK (diet_plan_recipe_id XOR user_recipe_id)
ALTER TABLE public.planned_meals DROP CONSTRAINT IF EXISTS chk_one_meal_type;
ALTER TABLE public.planned_meals ADD CONSTRAINT chk_one_meal_type CHECK (
    (diet_plan_recipe_id IS NOT NULL AND user_recipe_id IS NULL) OR
    (diet_plan_recipe_id IS NULL     AND user_recipe_id IS NOT NULL)
);

-- =============================================================================
-- SECTION 6: Actualizar funciones DB
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 6a. approve_free_recipe_as_global
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."approve_free_recipe_as_global"("p_free_recipe_id" bigint, "p_recipe_data" "jsonb", "p_ingredients" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
    v_user_id uuid;
    v_day_meal_id bigint;
    v_diet_plan_id bigint;
    new_recipe_id bigint;
    new_diet_plan_recipe_id bigint;
    ingredient_record jsonb;
    occurrence_record record;
BEGIN
    IF NOT is_admin() THEN
        RAISE EXCEPTION 'Only admins can perform this action';
    END IF;

    -- 1. Get info from the original user recipe (type='free')
    SELECT user_id, diet_plan_id, day_meal_id
    INTO v_user_id, v_diet_plan_id, v_day_meal_id
    FROM user_recipes
    WHERE id = p_free_recipe_id;

    -- 2. Create the new global recipe
    INSERT INTO recipes (name, instructions, prep_time_min, difficulty, created_by)
    VALUES (
        p_recipe_data->>'name',
        p_recipe_data->>'instructions',
        (p_recipe_data->>'prep_time_min')::integer,
        p_recipe_data->>'difficulty',
        auth.uid()
    )
    RETURNING id INTO new_recipe_id;

    -- 3. Insert ingredients for the global recipe
    FOR ingredient_record IN SELECT * FROM jsonb_array_elements(p_ingredients)
    LOOP
        INSERT INTO recipe_ingredients (recipe_id, food_id, grams, food_group_id)
        VALUES (
            new_recipe_id,
            (ingredient_record->>'food_id')::bigint,
            (ingredient_record->>'grams')::integer,
            (ingredient_record->>'food_group_id')::bigint
        );
    END LOOP;

    -- 4. Add the new recipe to the user's diet plan
    IF v_diet_plan_id IS NOT NULL THEN
        INSERT INTO diet_plan_recipes (
            diet_plan_id, recipe_id, day_meal_id, is_customized,
            custom_name, custom_instructions, custom_prep_time_min, custom_difficulty
        )
        VALUES (
            v_diet_plan_id, new_recipe_id, v_day_meal_id, true,
            p_recipe_data->>'name',
            p_recipe_data->>'instructions',
            (p_recipe_data->>'prep_time_min')::integer,
            p_recipe_data->>'difficulty'
        )
        RETURNING id INTO new_diet_plan_recipe_id;

        -- Insert ingredients for the diet plan recipe
        FOR ingredient_record IN SELECT * FROM jsonb_array_elements(p_ingredients)
        LOOP
            INSERT INTO recipe_ingredients (diet_plan_recipe_id, food_id, grams)
            VALUES (
                new_diet_plan_recipe_id,
                (ingredient_record->>'food_id')::bigint,
                (ingredient_record->>'grams')::integer
            );
        END LOOP;

        -- 5. Update daily_meal_logs to point to the new diet_plan_recipe
        FOR occurrence_record IN
            SELECT id FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id
        LOOP
            UPDATE daily_meal_logs
            SET
                diet_plan_recipe_id = new_diet_plan_recipe_id,
                free_recipe_occurrence_id = NULL
            WHERE free_recipe_occurrence_id = occurrence_record.id;
        END LOOP;

        -- 6. Migrate equivalence adjustments
        UPDATE equivalence_adjustments
        SET
            source_diet_plan_recipe_id = new_diet_plan_recipe_id,
            source_user_recipe_id = NULL
        WHERE source_user_recipe_id = p_free_recipe_id;

        -- 7. Clean up the original free recipe
        DELETE FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id;
        DELETE FROM recipe_ingredients WHERE user_recipe_id = p_free_recipe_id;
        UPDATE user_recipes SET source_user_recipe_id = NULL WHERE source_user_recipe_id = p_free_recipe_id;
        DELETE FROM user_recipes WHERE id = p_free_recipe_id;

        RETURN jsonb_build_object('success', true, 'recipeId', new_recipe_id, 'addedToPlan', true);
    ELSE
        RETURN jsonb_build_object('success', true, 'recipeId', new_recipe_id, 'addedToPlan', false, 'reason', 'No diet plan ID found on free recipe');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- ---------------------------------------------------------------------------
-- 6b. convert_free_to_private_recipe
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."convert_free_to_private_recipe"("p_free_recipe_id" bigint, "p_new_recipe_data" "jsonb", "p_new_ingredients" "jsonb") RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
    DECLARE
        v_user_id uuid;
        v_diet_plan_id bigint;
        v_day_meal_id bigint;
        new_user_recipe_id bigint;
        occurrence_record record;
        ingredient_record jsonb;
        is_coach boolean;
        is_admin_user boolean;
    BEGIN
        is_admin_user := is_admin();
        is_coach := EXISTS (
            SELECT 1 FROM user_roles ur
            JOIN roles r ON ur.role_id = r.id
            WHERE ur.user_id = auth.uid() AND r.role = 'coach'
        );

        -- 1. Get info from the original user recipe (type='free')
        SELECT user_id, diet_plan_id, day_meal_id
        INTO v_user_id, v_diet_plan_id, v_day_meal_id
        FROM user_recipes
        WHERE id = p_free_recipe_id;

        IF v_user_id IS NULL THEN
            RAISE EXCEPTION 'Free recipe not found';
        END IF;

        -- 2. Verify permissions
        IF NOT is_admin_user THEN
            IF is_coach THEN
                IF NOT EXISTS (SELECT 1 FROM coach_clients WHERE coach_id = auth.uid() AND client_id = v_user_id) THEN
                    RAISE EXCEPTION 'Permission denied: Client is not assigned to you.';
                END IF;
            ELSE
                RAISE EXCEPTION 'Only admins or assigned coaches can perform this action';
            END IF;
        END IF;

        -- 3. Create the new private recipe in user_recipes
        INSERT INTO user_recipes (
            user_id, type, name, instructions, prep_time_min, difficulty,
            diet_plan_id, day_meal_id, source_user_recipe_id
        )
        VALUES (
            v_user_id,
            'private',
            p_new_recipe_data->>'name',
            p_new_recipe_data->>'instructions',
            (p_new_recipe_data->>'prep_time_min')::integer,
            p_new_recipe_data->>'difficulty',
            v_diet_plan_id,
            v_day_meal_id,
            p_free_recipe_id
        )
        RETURNING id INTO new_user_recipe_id;

        -- 4. Copy ingredients to the new private recipe
        FOR ingredient_record IN SELECT * FROM jsonb_array_elements(p_new_ingredients)
        LOOP
            INSERT INTO recipe_ingredients (user_recipe_id, food_id, grams)
            VALUES (
                new_user_recipe_id,
                (ingredient_record->>'food_id')::bigint,
                (ingredient_record->>'grams')::numeric
            );
        END LOOP;

        -- 5. Update daily_meal_logs: replace occurrence link with direct user_recipe link
        FOR occurrence_record IN
            SELECT id FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id
        LOOP
            UPDATE daily_meal_logs
            SET
                user_recipe_id = new_user_recipe_id,
                free_recipe_occurrence_id = NULL
            WHERE free_recipe_occurrence_id = occurrence_record.id;
        END LOOP;

        -- 6. Migrate equivalence adjustments
        UPDATE equivalence_adjustments
        SET source_user_recipe_id = new_user_recipe_id
        WHERE source_user_recipe_id = p_free_recipe_id;

        -- 7. Clean up the original free recipe
        DELETE FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id;
        DELETE FROM recipe_ingredients WHERE user_recipe_id = p_free_recipe_id;
        DELETE FROM user_recipes WHERE id = p_free_recipe_id;

        RETURN new_user_recipe_id;
    END;
$$;

-- ---------------------------------------------------------------------------
-- 6c. delete_free_recipe_and_occurrences
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."delete_free_recipe_and_occurrences"("p_free_recipe_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
    DECLARE
        v_user_id uuid;
        is_coach boolean;
        is_admin_user boolean;
    BEGIN
        SELECT user_id INTO v_user_id FROM user_recipes WHERE id = p_free_recipe_id;

        IF v_user_id IS NULL THEN
             RAISE EXCEPTION 'Free recipe not found';
        END IF;

        is_admin_user := is_admin();
        is_coach := EXISTS (
            SELECT 1 FROM user_roles ur
            JOIN roles r ON ur.role_id = r.id
            WHERE ur.user_id = auth.uid() AND r.role = 'coach'
        );

        IF auth.uid() != v_user_id AND NOT is_admin_user THEN
             IF is_coach THEN
                IF NOT EXISTS (SELECT 1 FROM coach_clients WHERE coach_id = auth.uid() AND client_id = v_user_id) THEN
                    RAISE EXCEPTION 'Permission denied to delete this free recipe. Client not assigned.';
                END IF;
             ELSE
                RAISE EXCEPTION 'Permission denied to delete this free recipe.';
             END IF;
        END IF;

        DELETE FROM equivalence_adjustments
        WHERE source_user_recipe_id = p_free_recipe_id;

        DELETE FROM daily_meal_logs
        WHERE free_recipe_occurrence_id IN (
            SELECT id FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id
        );

        DELETE FROM free_recipe_occurrences WHERE user_recipe_id = p_free_recipe_id;
        DELETE FROM recipe_ingredients WHERE user_recipe_id = p_free_recipe_id;
        DELETE FROM user_recipes WHERE id = p_free_recipe_id;
    END;
$$;

-- ---------------------------------------------------------------------------
-- 6d. delete_private_recipe_cascade
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."delete_private_recipe_cascade"("p_recipe_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  child_id bigint;
  v_owner_user_id uuid;
  v_is_admin boolean;
  v_is_coach boolean;
begin
  select ur.user_id
  into v_owner_user_id
  from public.user_recipes ur
  where ur.id = p_recipe_id AND ur.type = 'private';

  if not found then
    raise exception 'Private recipe not found';
  end if;

  v_is_admin := public.is_admin();
  v_is_coach := exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.role = 'coach'
  );

  if auth.uid() is distinct from v_owner_user_id and not v_is_admin then
    if not v_is_coach or not exists (
      select 1
      from public.coach_clients cc
      where cc.coach_id = auth.uid()
        and cc.client_id = v_owner_user_id
    ) then
      raise exception 'Permission denied to delete this private recipe.';
    end if;
  end if;

  -- Recursively delete children (versioning chain)
  for child_id in
    select id
    from public.user_recipes
    where parent_user_recipe_id = p_recipe_id
      and type = 'private'
  loop
    perform public.delete_private_recipe_cascade(child_id);
  end loop;

  delete from public.diet_change_requests
  where user_recipe_id = p_recipe_id
     or requested_changes_user_recipe_id = p_recipe_id;

  delete from public.recipe_ingredients
  where user_recipe_id = p_recipe_id;

  delete from public.daily_meal_logs
  where user_recipe_id = p_recipe_id;

  delete from public.planned_meals
  where user_recipe_id = p_recipe_id;

  delete from public.daily_ingredient_adjustments
  where user_recipe_id = p_recipe_id;

  delete from public.daily_ingredient_adjustments
  where equivalence_adjustment_id in (
    select id
    from public.equivalence_adjustments
    where source_user_recipe_id = p_recipe_id
  );

  delete from public.equivalence_adjustments
  where source_user_recipe_id = p_recipe_id;

  delete from public.user_recipes
  where id = p_recipe_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6e. delete_user_complete
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."delete_user_complete"("p_user_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  plan_record record;
  food_record record;
begin
  if not is_admin() then
    raise exception 'Only admins can delete users.';
  end if;

  delete from daily_ingredient_adjustments
  where equivalence_adjustment_id in (
    select id from equivalence_adjustments where user_id = p_user_id
  );

  delete from equivalence_adjustments where user_id = p_user_id;

  for plan_record in select id from diet_plans where user_id = p_user_id loop
    perform delete_diet_plan_with_dependencies(plan_record.id);
  end loop;

  delete from daily_meal_logs where user_id = p_user_id;
  delete from daily_snack_logs where user_id = p_user_id;
  delete from daily_plan_snapshots where user_id = p_user_id;
  delete from plan_adherence_logs where user_id = p_user_id;
  delete from planned_meals where user_id = p_user_id;
  delete from diet_change_requests where user_id = p_user_id;

  delete from free_recipe_occurrences where user_id = p_user_id;
  delete from recipe_ingredients
  where user_recipe_id in (select id from user_recipes where user_id = p_user_id);
  delete from user_recipes where user_id = p_user_id;

  delete from snack_occurrences where user_id = p_user_id;
  delete from snack_ingredients where snack_id in (select id from snacks where user_id = p_user_id);
  delete from snacks where user_id = p_user_id;

  for food_record in select id from food where user_id = p_user_id loop
    perform delete_food_with_dependencies(food_record.id);
  end loop;

  delete from user_day_meals where user_id = p_user_id;
  delete from shopping_list_items where user_id = p_user_id;
  delete from private_shopping_list_items where user_id = p_user_id;
  delete from weight_logs where user_id = p_user_id;
  delete from diet_preferences where user_id = p_user_id;
  delete from training_preferences where user_id = p_user_id;
  delete from user_individual_food_restrictions where user_id = p_user_id;
  delete from user_medical_conditions where user_id = p_user_id;
  delete from user_sensitivities where user_id = p_user_id;
  delete from preferred_foods where user_id = p_user_id;
  delete from non_preferred_foods where user_id = p_user_id;
  delete from user_utilities where user_id = p_user_id;
  delete from user_notifications where user_id = p_user_id;
  delete from advisories where user_id = p_user_id;
  delete from reminders where user_id = p_user_id;

  delete from coach_clients where client_id = p_user_id or coach_id = p_user_id;
  delete from user_centers where user_id = p_user_id;
  delete from user_roles where user_id = p_user_id;

  update diet_plan_centers set assigned_by = null where assigned_by = p_user_id;

  delete from profiles where user_id = p_user_id;
  delete from auth.users where id = p_user_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6f. get_users_with_free_recipes_by_status
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."get_users_with_free_recipes_by_status"("p_status" "text") RETURNS TABLE("user_id" "uuid", "full_name" "text", "pending_count" integer)
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
begin
  return query
  select
    p.user_id,
    p.full_name,
    count(ur.id)::integer as pending_count
  from public.user_recipes ur
  join public.profiles p on ur.user_id = p.user_id
  where ur.type = 'free'
    and ur.status = p_status
  group by p.user_id, p.full_name
  having count(ur.id) > 0
  order by p.full_name;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6g. get_plan_items
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."get_plan_items"("p_user_id" "uuid", "p_plan_id" bigint, "p_start_date" "date", "p_end_date" "date") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'dietPlanRecipes', (
      select coalesce(jsonb_agg(dpr_agg), '[]'::jsonb)
      from (
        select
          dpr.*,
          r.name as recipe_name,
          r.instructions as recipe_instructions,
          r.prep_time_min as recipe_prep_time,
          r.difficulty as recipe_difficulty,
          (
            select jsonb_agg(jsonb_build_object('food_id', ri.food_id, 'grams', ri.grams))
            from recipe_ingredients ri where ri.recipe_id = dpr.recipe_id
          ) as recipe_ingredients,
          dm.name as day_meal_name
        from diet_plan_recipes dpr
        join recipes r on dpr.recipe_id = r.id
        join day_meals dm on dpr.day_meal_id = dm.id
        where dpr.diet_plan_id = p_plan_id
      ) dpr_agg
    ),
    'privateRecipes', (
      select coalesce(jsonb_agg(ur_agg), '[]'::jsonb)
      from (
        select ur.*
        from user_recipes ur
        where ur.user_id = p_user_id
          and ur.diet_plan_id = p_plan_id
          and ur.type = 'private'
      ) ur_agg
    ),
    'freeMeals', (
      select coalesce(jsonb_agg(fm_agg), '[]'::jsonb)
      from (
        select
          fro.*,
          ur.name,
          ur.instructions,
          ur.prep_time_min,
          ur.difficulty,
          ur.day_meal_id,
          (
            select jsonb_agg(jsonb_build_object('food_id', ri.food_id, 'grams', ri.grams))
            from recipe_ingredients ri
            where ri.user_recipe_id = ur.id
          ) as recipe_ingredients,
          fro.id as occurrence_id
        from free_recipe_occurrences fro
        join user_recipes ur on fro.user_recipe_id = ur.id
        where fro.user_id = p_user_id
          and (ur.diet_plan_id = p_plan_id or ur.diet_plan_id is null)
          and ur.type = 'free'
          and fro.meal_date between p_start_date and p_end_date
      ) fm_agg
    ),
    'mealLogs', (
      select coalesce(jsonb_agg(dml), '[]'::jsonb) from daily_meal_logs dml
      where dml.user_id = p_user_id and dml.log_date between p_start_date and p_end_date
    ),
    'userDayMeals', (
      select coalesce(jsonb_agg(udm_agg), '[]'::jsonb)
      from (
        select udm.*, dm.name as day_meal_name, dm.display_order
        from user_day_meals udm
        join day_meals dm on udm.day_meal_id = dm.id
        where udm.user_id = p_user_id
        order by dm.display_order
      ) udm_agg
    )
  ) into result;

  return result;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6h. update_free_recipe
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."update_free_recipe"("p_recipe_id" bigint, "p_name" "text", "p_instructions" "text", "p_prep_time_min" integer, "p_difficulty" "text", "p_ingredients" "jsonb") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  ingredient_record jsonb;
  v_owner_user_id uuid;
  v_is_admin boolean;
  v_is_coach boolean;
begin
  select ur.user_id
  into v_owner_user_id
  from public.user_recipes ur
  where ur.id = p_recipe_id AND ur.type = 'free';

  if not found then
    raise exception 'Free recipe not found';
  end if;

  v_is_admin := public.is_admin();
  v_is_coach := exists (
    select 1
    from public.user_roles ur2
    join public.roles r on r.id = ur2.role_id
    where ur2.user_id = auth.uid()
      and r.role = 'coach'
  );

  if auth.uid() is distinct from v_owner_user_id and not v_is_admin then
    if not v_is_coach or not exists (
      select 1
      from public.coach_clients cc
      where cc.coach_id = auth.uid()
        and cc.client_id = v_owner_user_id
    ) then
      raise exception 'Permission denied to update this free recipe.';
    end if;
  end if;

  update public.user_recipes
  set
    name = p_name,
    instructions = p_instructions,
    prep_time_min = p_prep_time_min,
    difficulty = p_difficulty
  where id = p_recipe_id;

  delete from public.recipe_ingredients
  where user_recipe_id = p_recipe_id;

  for ingredient_record in
    select *
    from jsonb_array_elements(coalesce(p_ingredients, '[]'::jsonb))
  loop
    insert into public.recipe_ingredients (user_recipe_id, food_id, grams, status)
    values (
      p_recipe_id,
      (ingredient_record->>'food_id')::bigint,
      (ingredient_record->>'grams')::numeric,
      case
        when lower(coalesce(ingredient_record->>'status', '')) = 'pending' then 'pending'
        when lower(coalesce(ingredient_record->>'status', '')) = 'rejected' then 'rejected'
        else 'linked'
      end
    );
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6i. update_private_recipe
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."update_private_recipe"("p_recipe_id" bigint, "p_name" "text", "p_instructions" "text", "p_prep_time_min" integer, "p_difficulty" "text", "p_ingredients" "jsonb") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  ingredient_record jsonb;
  v_owner_user_id uuid;
  v_is_admin boolean;
  v_is_coach boolean;
begin
  select ur.user_id
  into v_owner_user_id
  from public.user_recipes ur
  where ur.id = p_recipe_id AND ur.type = 'private';

  if not found then
    raise exception 'Private recipe not found';
  end if;

  v_is_admin := public.is_admin();
  v_is_coach := exists (
    select 1
    from public.user_roles ur2
    join public.roles r on r.id = ur2.role_id
    where ur2.user_id = auth.uid()
      and r.role = 'coach'
  );

  if auth.uid() is distinct from v_owner_user_id and not v_is_admin then
    if not v_is_coach or not exists (
      select 1
      from public.coach_clients cc
      where cc.coach_id = auth.uid()
        and cc.client_id = v_owner_user_id
    ) then
      raise exception 'Permission denied to update this private recipe.';
    end if;
  end if;

  update public.user_recipes
  set
    name = p_name,
    instructions = p_instructions,
    prep_time_min = p_prep_time_min,
    difficulty = p_difficulty
  where id = p_recipe_id;

  delete from public.recipe_ingredients
  where user_recipe_id = p_recipe_id;

  for ingredient_record in
    select *
    from jsonb_array_elements(coalesce(p_ingredients, '[]'::jsonb))
  loop
    insert into public.recipe_ingredients (user_recipe_id, food_id, grams)
    values (
      p_recipe_id,
      (ingredient_record->>'food_id')::bigint,
      (ingredient_record->>'grams')::numeric
    );
  end loop;
end;
$$;

-- =============================================================================
-- SECTION 7: Actualizar trigger de notificación
-- =============================================================================

-- Actualizar la función de notificación (no accede a source_free_recipe_id ya)
CREATE OR REPLACE FUNCTION "public"."create_private_recipe_notification"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.user_notifications (user_id, title, message, type)
  values (
    new.user_id,
    '¡Receta Guardada!',
    '¡Tu receta libre "' || new.name || '" ha sido tan buena que ha sido guardada en tu plan para que la disfrutes cuando quieras!',
    'free_recipe_saved'
  );
  return new;
end;
$$;

-- Eliminar trigger antiguo sobre private_recipes (tabla que se va a eliminar)
DROP TRIGGER IF EXISTS "on_private_recipe_creation_from_free_meal" ON public.private_recipes;

-- Crear trigger equivalente sobre user_recipes
CREATE OR REPLACE TRIGGER "on_user_recipe_conversion_from_free"
AFTER INSERT ON public.user_recipes
FOR EACH ROW
WHEN (NEW.type = 'private' AND NEW.source_user_recipe_id IS NOT NULL)
EXECUTE FUNCTION public.create_private_recipe_notification();

-- =============================================================================
-- SECTION 8: RLS policies para user_recipes
-- =============================================================================

ALTER TABLE public.user_recipes ENABLE ROW LEVEL SECURITY;

-- Admin: acceso total
CREATE POLICY "Allow admin full access on user_recipes"
ON public.user_recipes
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- Usuarios: gestionar las suyas
CREATE POLICY "Allow users to manage their own user_recipes"
ON public.user_recipes
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Coaches: gestionar las de sus clientes
CREATE POLICY "Coaches can manage client user_recipes"
ON public.user_recipes
USING (
    EXISTS (
        SELECT 1 FROM public.coach_clients cc
        WHERE cc.coach_id = auth.uid() AND cc.client_id = user_recipes.user_id
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.coach_clients cc
        WHERE cc.coach_id = auth.uid() AND cc.client_id = user_recipes.user_id
    )
);

-- =============================================================================
-- SECTION 9: Actualizar RLS de recipe_ingredients (quitar políticas de free/private)
-- =============================================================================

-- Eliminar políticas que aún referencian free_recipe_id o private_recipe_id
-- (pueden existir con varios nombres; usamos IF EXISTS)
DO $$
DECLARE
    pol_name text;
BEGIN
    FOR pol_name IN
        SELECT policyname FROM pg_policies
        WHERE tablename = 'recipe_ingredients'
          AND (qual ILIKE '%free_recipe_id%' OR qual ILIKE '%private_recipe_id%'
            OR with_check ILIKE '%free_recipe_id%' OR with_check ILIKE '%private_recipe_id%')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.recipe_ingredients', pol_name);
        RAISE NOTICE 'Dropped RLS policy: %', pol_name;
    END LOOP;
END $$;

-- Añadir políticas para user_recipe_id
CREATE POLICY "Users manage own user_recipe ingredients"
ON public.recipe_ingredients
FOR ALL
USING (
    user_recipe_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.user_recipes ur
        WHERE ur.id = recipe_ingredients.user_recipe_id
          AND ur.user_id = auth.uid()
    )
)
WITH CHECK (
    user_recipe_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.user_recipes ur
        WHERE ur.id = recipe_ingredients.user_recipe_id
          AND ur.user_id = auth.uid()
    )
);

CREATE POLICY "Coaches manage client user_recipe ingredients"
ON public.recipe_ingredients
FOR ALL
USING (
    user_recipe_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.user_recipes ur
        JOIN public.coach_clients cc ON cc.client_id = ur.user_id
        WHERE ur.id = recipe_ingredients.user_recipe_id
          AND cc.coach_id = auth.uid()
    )
)
WITH CHECK (
    user_recipe_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.user_recipes ur
        JOIN public.coach_clients cc ON cc.client_id = ur.user_id
        WHERE ur.id = recipe_ingredients.user_recipe_id
          AND cc.coach_id = auth.uid()
    )
);

-- =============================================================================
-- SECTION 10: DROP tablas originales, crear vistas de compatibilidad
-- =============================================================================

-- Eliminar trigger en free_recipe_occurrences que ya no tiene free_recipe_id
-- (verificar si hay triggers sobre estas tablas)
-- Ya no hay FKs desde otros lados apuntando a free_recipes excepto private_recipes.source_free_recipe_id
-- que se elimina al dropear private_recipes.

-- DROP TABLE private_recipes primero (elimina FK de private_recipes → free_recipes)
DROP TABLE IF EXISTS public.private_recipes CASCADE;

-- DROP TABLE free_recipes
DROP TABLE IF EXISTS public.free_recipes CASCADE;

-- Crear vistas de compatibilidad (read-only)
CREATE OR REPLACE VIEW public.free_recipes AS
SELECT
    id,
    user_id,
    created_at,
    day_meal_id,
    name,
    instructions,
    status,
    diet_plan_id,
    prep_time_min,
    difficulty,
    parent_user_recipe_id AS parent_free_recipe_id,
    parent_recipe_id,
    source_user_recipe_id AS source_free_recipe_id
FROM public.user_recipes
WHERE type = 'free';

CREATE OR REPLACE VIEW public.private_recipes AS
SELECT
    id,
    user_id,
    source_user_recipe_id AS source_free_recipe_id,
    name,
    instructions,
    created_at,
    diet_plan_id,
    day_meal_id,
    prep_time_min,
    difficulty,
    parent_user_recipe_id AS parent_private_recipe_id
FROM public.user_recipes
WHERE type = 'private';

ALTER VIEW public.free_recipes OWNER TO postgres;
ALTER VIEW public.private_recipes OWNER TO postgres;

-- =============================================================================
-- SECTION 11: Actualizar vistas de compatibilidad de ingredientes (de Fase 1)
-- =============================================================================

-- free_recipe_ingredients: era "WHERE free_recipe_id IS NOT NULL",
-- ahora necesita unirse con user_recipes para filtrar por type='free'
CREATE OR REPLACE VIEW public.free_recipe_ingredients AS
SELECT
    ri.id,
    ri.user_recipe_id AS free_recipe_id,
    ri.food_id,
    ri.grams,
    ri.status,
    ri.created_at
FROM public.recipe_ingredients ri
JOIN public.user_recipes ur ON ur.id = ri.user_recipe_id
WHERE ur.type = 'free';

ALTER VIEW public.free_recipe_ingredients OWNER TO postgres;

-- private_recipe_ingredients: análogo
CREATE OR REPLACE VIEW public.private_recipe_ingredients AS
SELECT
    ri.id,
    ri.user_recipe_id AS private_recipe_id,
    ri.food_id,
    ri.grams,
    ri.created_at
FROM public.recipe_ingredients ri
JOIN public.user_recipes ur ON ur.id = ri.user_recipe_id
WHERE ur.type = 'private';

ALTER VIEW public.private_recipe_ingredients OWNER TO postgres;

-- =============================================================================
-- SECTION 12: Limpiar columnas temporales de tracking
-- =============================================================================

ALTER TABLE public.user_recipes
    DROP COLUMN IF EXISTS _src_table,
    DROP COLUMN IF EXISTS _src_id;

-- =============================================================================
-- SECTION 13: GRANTS
-- =============================================================================

GRANT ALL ON TABLE public.user_recipes TO anon;
GRANT ALL ON TABLE public.user_recipes TO authenticated;
GRANT ALL ON TABLE public.user_recipes TO service_role;
GRANT ALL ON SEQUENCE public.user_recipes_id_seq TO anon;
GRANT ALL ON SEQUENCE public.user_recipes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.user_recipes_id_seq TO service_role;

GRANT ALL ON TABLE public.free_recipes TO anon;
GRANT ALL ON TABLE public.free_recipes TO authenticated;
GRANT ALL ON TABLE public.free_recipes TO service_role;

GRANT ALL ON TABLE public.private_recipes TO anon;
GRANT ALL ON TABLE public.private_recipes TO authenticated;
GRANT ALL ON TABLE public.private_recipes TO service_role;

-- =============================================================================
-- SECTION 14: Verificación final
-- =============================================================================

DO $$
DECLARE
    ur_count  integer;
    ri_free   integer;
BEGIN
    SELECT COUNT(*) INTO ur_count FROM public.user_recipes;
    SELECT COUNT(*) INTO ri_free FROM public.recipe_ingredients WHERE user_recipe_id IS NOT NULL;

    RAISE NOTICE '=== VERIFICACIÓN FASE 2 ===';
    RAISE NOTICE 'user_recipes total: %', ur_count;
    RAISE NOTICE 'recipe_ingredients con user_recipe_id: %', ri_free;

    -- Comprobar que no quedan columnas antiguas
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'recipe_ingredients'
          AND column_name IN ('free_recipe_id', 'private_recipe_id')
    ) THEN
        RAISE EXCEPTION 'Aún existen columnas antiguas en recipe_ingredients!';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'planned_meals'
          AND column_name IN ('free_recipe_id', 'private_recipe_id')
    ) THEN
        RAISE EXCEPTION 'Aún existen columnas antiguas en planned_meals!';
    END IF;

    RAISE NOTICE '=== Migración Fase 2 completada con éxito ===';
END $$;

COMMIT;
