BEGIN;

ALTER TABLE public.invitation_links
  ADD COLUMN IF NOT EXISTS last_used_at timestamptz;

CREATE TABLE IF NOT EXISTS public.invitation_link_usages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invitation_link_id uuid NOT NULL REFERENCES public.invitation_links(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  consumed_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'web'
    CONSTRAINT invitation_link_usages_source_check
    CHECK (
      source IN (
        'web',
        'login_password',
        'signup_auto_session',
        'auth_state_signed_in',
        'session_bootstrap',
        'oauth_google'
      )
    ),
  user_agent text,
  assigned_role_id integer NOT NULL REFERENCES public.roles(id),
  assigned_center_id bigint REFERENCES public.centers(id) ON DELETE SET NULL,
  UNIQUE(invitation_link_id, user_id)
);

ALTER TABLE public.invitation_link_usages OWNER TO postgres;

CREATE INDEX IF NOT EXISTS invitation_link_usages_invitation_id_idx
  ON public.invitation_link_usages(invitation_link_id, consumed_at DESC);

CREATE INDEX IF NOT EXISTS invitation_link_usages_user_id_idx
  ON public.invitation_link_usages(user_id, consumed_at DESC);

ALTER TABLE public.invitation_link_usages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin read invitation link usages" ON public.invitation_link_usages;
CREATE POLICY "Admin read invitation link usages"
  ON public.invitation_link_usages
  FOR SELECT
  USING (public.is_admin());

GRANT SELECT ON public.invitation_link_usages TO authenticated;
GRANT ALL ON public.invitation_link_usages TO service_role;

CREATE OR REPLACE FUNCTION public.admin_create_invitation_link(
  p_destination text DEFAULT 'login',
  p_role_id integer DEFAULT NULL,
  p_center_id bigint DEFAULT NULL,
  p_max_uses integer DEFAULT 1,
  p_note text DEFAULT NULL,
  p_expires_at timestamptz DEFAULT NULL
)
RETURNS public.invitation_links
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now timestamptz := now();
  v_token text;
  v_invitation public.invitation_links;
  v_role_name text;
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_admin() THEN
    RAISE EXCEPTION 'Only admins can create invitation links.';
  END IF;

  IF COALESCE(trim(p_destination), '') <> 'login' THEN
    RAISE EXCEPTION 'Unsupported destination: %', p_destination;
  END IF;

  IF p_role_id IS NULL THEN
    RAISE EXCEPTION 'Role is required.';
  END IF;

  SELECT r.role
  INTO v_role_name
  FROM public.roles r
  WHERE r.id = p_role_id;

  IF v_role_name IS NULL THEN
    RAISE EXCEPTION 'Role not found: %', p_role_id;
  END IF;

  IF lower(v_role_name) NOT IN ('free', 'client', 'coach') THEN
    RAISE EXCEPTION 'Invitations can only assign free/client/coach roles.';
  END IF;

  IF p_center_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.centers c
    WHERE c.id = p_center_id
  ) THEN
    RAISE EXCEPTION 'Center not found: %', p_center_id;
  END IF;

  IF p_max_uses IS NOT NULL AND p_max_uses <= 0 THEN
    RAISE EXCEPTION 'max_uses must be greater than 0 when present.';
  END IF;

  IF p_expires_at IS NOT NULL AND p_expires_at <= v_now THEN
    RAISE EXCEPTION 'Expiration must be in the future.';
  END IF;

  LOOP
    v_token := lower(replace(gen_random_uuid()::text, '-', ''))
      || substr(lower(replace(gen_random_uuid()::text, '-', '')), 1, 8);

    EXIT WHEN NOT EXISTS (
      SELECT 1
      FROM public.invitation_links il
      WHERE il.token = v_token
    );
  END LOOP;

  INSERT INTO public.invitation_links (
    token,
    destination,
    role_id,
    center_id,
    max_uses,
    note,
    expires_at,
    created_by
  )
  VALUES (
    v_token,
    'login',
    p_role_id,
    p_center_id,
    p_max_uses,
    NULLIF(trim(p_note), ''),
    p_expires_at,
    auth.uid()
  )
  RETURNING * INTO v_invitation;

  RETURN v_invitation;
END;
$$;

ALTER FUNCTION public.admin_create_invitation_link(
  text,
  integer,
  bigint,
  integer,
  text,
  timestamptz
) OWNER TO postgres;

CREATE OR REPLACE FUNCTION public.redeem_invitation_link(
  p_token text,
  p_source text DEFAULT 'web',
  p_user_agent text DEFAULT NULL
)
RETURNS TABLE(
  status text,
  invitation_link_id uuid,
  role_id integer,
  center_id bigint,
  used_uses integer,
  max_uses integer,
  expires_at timestamptz,
  is_revoked boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now timestamptz := now();
  v_token text := lower(trim(COALESCE(p_token, '')));
  v_source text := lower(trim(COALESCE(p_source, 'web')));
  v_invitation public.invitation_links%ROWTYPE;
  v_usage_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required to redeem invitation links.';
  END IF;

  IF v_source NOT IN (
    'web',
    'login_password',
    'signup_auto_session',
    'auth_state_signed_in',
    'session_bootstrap',
    'oauth_google'
  ) THEN
    v_source := 'web';
  END IF;

  IF v_token = '' THEN
    RETURN QUERY SELECT
      'missing_token'::text,
      NULL::uuid,
      NULL::integer,
      NULL::bigint,
      NULL::integer,
      NULL::integer,
      NULL::timestamptz,
      NULL::boolean;
    RETURN;
  END IF;

  SELECT *
  INTO v_invitation
  FROM public.invitation_links il
  WHERE il.token = v_token
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN QUERY SELECT
      'invalid_token'::text,
      NULL::uuid,
      NULL::integer,
      NULL::bigint,
      NULL::integer,
      NULL::integer,
      NULL::timestamptz,
      NULL::boolean;
    RETURN;
  END IF;

  SELECT iu.id
  INTO v_usage_id
  FROM public.invitation_link_usages iu
  WHERE iu.invitation_link_id = v_invitation.id
    AND iu.user_id = auth.uid()
  LIMIT 1;

  IF v_usage_id IS NOT NULL THEN
    INSERT INTO public.user_roles (user_id, role_id)
    VALUES (auth.uid(), v_invitation.role_id)
    ON CONFLICT (user_id) DO UPDATE
      SET role_id = EXCLUDED.role_id;

    IF v_invitation.center_id IS NOT NULL THEN
      DELETE FROM public.user_centers uc
      WHERE uc.user_id = auth.uid()
        AND uc.center_id IS DISTINCT FROM v_invitation.center_id;

      INSERT INTO public.user_centers (user_id, center_id)
      VALUES (auth.uid(), v_invitation.center_id)
      ON CONFLICT (user_id, center_id) DO NOTHING;
    END IF;

    RETURN QUERY SELECT
      'already_redeemed'::text,
      v_invitation.id,
      v_invitation.role_id,
      v_invitation.center_id,
      v_invitation.used_uses,
      v_invitation.max_uses,
      v_invitation.expires_at,
      v_invitation.is_revoked;
    RETURN;
  END IF;

  IF v_invitation.is_revoked THEN
    RETURN QUERY SELECT
      'revoked'::text,
      v_invitation.id,
      v_invitation.role_id,
      v_invitation.center_id,
      v_invitation.used_uses,
      v_invitation.max_uses,
      v_invitation.expires_at,
      v_invitation.is_revoked;
    RETURN;
  END IF;

  IF v_invitation.expires_at IS NOT NULL AND v_invitation.expires_at <= v_now THEN
    RETURN QUERY SELECT
      'expired'::text,
      v_invitation.id,
      v_invitation.role_id,
      v_invitation.center_id,
      v_invitation.used_uses,
      v_invitation.max_uses,
      v_invitation.expires_at,
      v_invitation.is_revoked;
    RETURN;
  END IF;

  IF v_invitation.max_uses IS NOT NULL AND v_invitation.used_uses >= v_invitation.max_uses THEN
    RETURN QUERY SELECT
      'exhausted'::text,
      v_invitation.id,
      v_invitation.role_id,
      v_invitation.center_id,
      v_invitation.used_uses,
      v_invitation.max_uses,
      v_invitation.expires_at,
      v_invitation.is_revoked;
    RETURN;
  END IF;

  INSERT INTO public.user_roles (user_id, role_id)
  VALUES (auth.uid(), v_invitation.role_id)
  ON CONFLICT (user_id) DO UPDATE
    SET role_id = EXCLUDED.role_id;

  IF v_invitation.center_id IS NOT NULL THEN
    DELETE FROM public.user_centers uc
    WHERE uc.user_id = auth.uid()
      AND uc.center_id IS DISTINCT FROM v_invitation.center_id;

    INSERT INTO public.user_centers (user_id, center_id)
    VALUES (auth.uid(), v_invitation.center_id)
    ON CONFLICT (user_id, center_id) DO NOTHING;
  END IF;

  INSERT INTO public.invitation_link_usages (
    invitation_link_id,
    user_id,
    consumed_at,
    source,
    user_agent,
    assigned_role_id,
    assigned_center_id
  )
  VALUES (
    v_invitation.id,
    auth.uid(),
    v_now,
    v_source,
    left(NULLIF(trim(COALESCE(p_user_agent, '')), ''), 1024),
    v_invitation.role_id,
    v_invitation.center_id
  )
  ON CONFLICT (invitation_link_id, user_id) DO NOTHING
  RETURNING id INTO v_usage_id;

  IF v_usage_id IS NULL THEN
    RETURN QUERY SELECT
      'already_redeemed'::text,
      v_invitation.id,
      v_invitation.role_id,
      v_invitation.center_id,
      v_invitation.used_uses,
      v_invitation.max_uses,
      v_invitation.expires_at,
      v_invitation.is_revoked;
    RETURN;
  END IF;

  UPDATE public.invitation_links il
  SET
    used_uses = il.used_uses + 1,
    last_used_at = v_now
  WHERE il.id = v_invitation.id
  RETURNING * INTO v_invitation;

  RETURN QUERY SELECT
    'applied'::text,
    v_invitation.id,
    v_invitation.role_id,
    v_invitation.center_id,
    v_invitation.used_uses,
    v_invitation.max_uses,
    v_invitation.expires_at,
    v_invitation.is_revoked;
END;
$$;

ALTER FUNCTION public.redeem_invitation_link(text, text, text) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.redeem_invitation_link(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_invitation_link(text, text, text) FROM anon;
REVOKE ALL ON FUNCTION public.redeem_invitation_link(text, text, text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_invitation_link(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_invitation_link(text, text, text) TO service_role;

COMMIT;
