// Prefijos telefónicos internacionales ordenados numéricamente por código de marcación.
// El valor almacenado en DB es E.164: `${code}${number}` → ej. +34600000000
// Los emojis de bandera y nombres de país son solo para la UI, nunca se persisten.

export const PHONE_PREFIXES = [
  { code: '+1',   flag: '🇺🇸', name: 'EEUU / Canadá' },
  { code: '+7',   flag: '🇷🇺', name: 'Rusia' },
  { code: '+20',  flag: '🇪🇬', name: 'Egipto' },
  { code: '+27',  flag: '🇿🇦', name: 'Sudáfrica' },
  { code: '+30',  flag: '🇬🇷', name: 'Grecia' },
  { code: '+31',  flag: '🇳🇱', name: 'Países Bajos' },
  { code: '+32',  flag: '🇧🇪', name: 'Bélgica' },
  { code: '+33',  flag: '🇫🇷', name: 'Francia' },
  { code: '+34',  flag: '🇪🇸', name: 'España' },
  { code: '+36',  flag: '🇭🇺', name: 'Hungría' },
  { code: '+39',  flag: '🇮🇹', name: 'Italia' },
  { code: '+40',  flag: '🇷🇴', name: 'Rumanía' },
  { code: '+41',  flag: '🇨🇭', name: 'Suiza' },
  { code: '+43',  flag: '🇦🇹', name: 'Austria' },
  { code: '+44',  flag: '🇬🇧', name: 'Reino Unido' },
  { code: '+45',  flag: '🇩🇰', name: 'Dinamarca' },
  { code: '+46',  flag: '🇸🇪', name: 'Suecia' },
  { code: '+47',  flag: '🇳🇴', name: 'Noruega' },
  { code: '+48',  flag: '🇵🇱', name: 'Polonia' },
  { code: '+49',  flag: '🇩🇪', name: 'Alemania' },
  { code: '+51',  flag: '🇵🇪', name: 'Perú' },
  { code: '+52',  flag: '🇲🇽', name: 'México' },
  { code: '+53',  flag: '🇨🇺', name: 'Cuba' },
  { code: '+54',  flag: '🇦🇷', name: 'Argentina' },
  { code: '+55',  flag: '🇧🇷', name: 'Brasil' },
  { code: '+56',  flag: '🇨🇱', name: 'Chile' },
  { code: '+57',  flag: '🇨🇴', name: 'Colombia' },
  { code: '+58',  flag: '🇻🇪', name: 'Venezuela' },
  { code: '+60',  flag: '🇲🇾', name: 'Malasia' },
  { code: '+61',  flag: '🇦🇺', name: 'Australia' },
  { code: '+62',  flag: '🇮🇩', name: 'Indonesia' },
  { code: '+63',  flag: '🇵🇭', name: 'Filipinas' },
  { code: '+64',  flag: '🇳🇿', name: 'Nueva Zelanda' },
  { code: '+65',  flag: '🇸🇬', name: 'Singapur' },
  { code: '+66',  flag: '🇹🇭', name: 'Tailandia' },
  { code: '+81',  flag: '🇯🇵', name: 'Japón' },
  { code: '+82',  flag: '🇰🇷', name: 'Corea del Sur' },
  { code: '+84',  flag: '🇻🇳', name: 'Vietnam' },
  { code: '+86',  flag: '🇨🇳', name: 'China' },
  { code: '+90',  flag: '🇹🇷', name: 'Turquía' },
  { code: '+91',  flag: '🇮🇳', name: 'India' },
  { code: '+92',  flag: '🇵🇰', name: 'Pakistán' },
  { code: '+93',  flag: '🇦🇫', name: 'Afganistán' },
  { code: '+94',  flag: '🇱🇰', name: 'Sri Lanka' },
  { code: '+95',  flag: '🇲🇲', name: 'Myanmar' },
  { code: '+98',  flag: '🇮🇷', name: 'Irán' },
  { code: '+212', flag: '🇲🇦', name: 'Marruecos' },
  { code: '+213', flag: '🇩🇿', name: 'Argelia' },
  { code: '+216', flag: '🇹🇳', name: 'Túnez' },
  { code: '+218', flag: '🇱🇾', name: 'Libia' },
  { code: '+221', flag: '🇸🇳', name: 'Senegal' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria' },
  { code: '+237', flag: '🇨🇲', name: 'Camerún' },
  { code: '+243', flag: '🇨🇩', name: 'R. D. Congo' },
  { code: '+244', flag: '🇦🇴', name: 'Angola' },
  { code: '+250', flag: '🇷🇼', name: 'Ruanda' },
  { code: '+251', flag: '🇪🇹', name: 'Etiopía' },
  { code: '+254', flag: '🇰🇪', name: 'Kenia' },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania' },
  { code: '+256', flag: '🇺🇬', name: 'Uganda' },
  { code: '+258', flag: '🇲🇿', name: 'Mozambique' },
  { code: '+260', flag: '🇿🇲', name: 'Zambia' },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabue' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal' },
  { code: '+352', flag: '🇱🇺', name: 'Luxemburgo' },
  { code: '+353', flag: '🇮🇪', name: 'Irlanda' },
  { code: '+354', flag: '🇮🇸', name: 'Islandia' },
  { code: '+355', flag: '🇦🇱', name: 'Albania' },
  { code: '+356', flag: '🇲🇹', name: 'Malta' },
  { code: '+357', flag: '🇨🇾', name: 'Chipre' },
  { code: '+358', flag: '🇫🇮', name: 'Finlandia' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria' },
  { code: '+370', flag: '🇱🇹', name: 'Lituania' },
  { code: '+371', flag: '🇱🇻', name: 'Letonia' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia' },
  { code: '+373', flag: '🇲🇩', name: 'Moldavia' },
  { code: '+374', flag: '🇦🇲', name: 'Armenia' },
  { code: '+375', flag: '🇧🇾', name: 'Bielorrusia' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra' },
  { code: '+380', flag: '🇺🇦', name: 'Ucrania' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro' },
  { code: '+385', flag: '🇭🇷', name: 'Croacia' },
  { code: '+386', flag: '🇸🇮', name: 'Eslovenia' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia y Herz.' },
  { code: '+389', flag: '🇲🇰', name: 'Macedonia del Norte' },
  { code: '+420', flag: '🇨🇿', name: 'Rep. Checa' },
  { code: '+421', flag: '🇸🇰', name: 'Eslovaquia' },
  { code: '+423', flag: '🇱🇮', name: 'Liechtenstein' },
  { code: '+501', flag: '🇧🇿', name: 'Belice' },
  { code: '+502', flag: '🇬🇹', name: 'Guatemala' },
  { code: '+503', flag: '🇸🇻', name: 'El Salvador' },
  { code: '+504', flag: '🇭🇳', name: 'Honduras' },
  { code: '+505', flag: '🇳🇮', name: 'Nicaragua' },
  { code: '+506', flag: '🇨🇷', name: 'Costa Rica' },
  { code: '+507', flag: '🇵🇦', name: 'Panamá' },
  { code: '+509', flag: '🇭🇹', name: 'Haití' },
  { code: '+591', flag: '🇧🇴', name: 'Bolivia' },
  { code: '+592', flag: '🇬🇾', name: 'Guyana' },
  { code: '+593', flag: '🇪🇨', name: 'Ecuador' },
  { code: '+595', flag: '🇵🇾', name: 'Paraguay' },
  { code: '+597', flag: '🇸🇷', name: 'Surinam' },
  { code: '+598', flag: '🇺🇾', name: 'Uruguay' },
  { code: '+673', flag: '🇧🇳', name: 'Brunéi' },
  { code: '+675', flag: '🇵🇬', name: 'Papúa N. Guinea' },
  { code: '+679', flag: '🇫🇯', name: 'Fiyi' },
  { code: '+852', flag: '🇭🇰', name: 'Hong Kong' },
  { code: '+853', flag: '🇲🇴', name: 'Macao' },
  { code: '+855', flag: '🇰🇭', name: 'Camboya' },
  { code: '+856', flag: '🇱🇦', name: 'Laos' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladesh' },
  { code: '+886', flag: '🇹🇼', name: 'Taiwán' },
  { code: '+960', flag: '🇲🇻', name: 'Maldivas' },
  { code: '+961', flag: '🇱🇧', name: 'Líbano' },
  { code: '+962', flag: '🇯🇴', name: 'Jordania' },
  { code: '+963', flag: '🇸🇾', name: 'Siria' },
  { code: '+964', flag: '🇮🇶', name: 'Irak' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait' },
  { code: '+966', flag: '🇸🇦', name: 'Arabia Saudí' },
  { code: '+967', flag: '🇾🇪', name: 'Yemen' },
  { code: '+968', flag: '🇴🇲', name: 'Omán' },
  { code: '+971', flag: '🇦🇪', name: 'Emiratos Árabes' },
  { code: '+972', flag: '🇮🇱', name: 'Israel' },
  { code: '+973', flag: '🇧🇭', name: 'Baréin' },
  { code: '+974', flag: '🇶🇦', name: 'Catar' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal' },
  { code: '+992', flag: '🇹🇯', name: 'Tayikistán' },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistán' },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaiyán' },
  { code: '+995', flag: '🇬🇪', name: 'Georgia' },
  { code: '+996', flag: '🇰🇬', name: 'Kirguistán' },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistán' },
];

// E.164: + código de país + 6-14 dígitos locales, máximo 15 dígitos totales (ITU-T E.164)
export const validatePhone = (prefix, number) => {
  if (!number) return null; // campo opcional
  if (!/^\d+$/.test(number)) return 'Solo se permiten dígitos';
  if (number.length < 6) return 'Demasiado corto (mínimo 6 dígitos)';
  const totalDigits = prefix.replace('+', '').length + number.length;
  if (totalDigits > 15) return 'Demasiado largo (máximo 15 dígitos en total)';
  return null;
};

// Construye el número en formato E.164 listo para guardar en DB
// Devuelve null si el número local está vacío (campo opcional)
export const buildE164 = (prefix, number) => {
  if (!number) return null;
  return `${prefix}${number}`;
};
